### ISSUE TITLE
导出的结果只是源代码

### ISSUE THREAD

**Issue by chenxin0397** [mokeyish/obsidian-enhancing-export#1]
1.用dataview插件生成的表格用OB导出的PDF也都是渲染之后的结果，
2.在没有严格换行的情况下导出的word文件都没断行
3.在插件市还找不到该插件，只能手动安装

**Comment by mokeyish** [comment]
- 插件今天刚提交给官方，他们合并就能在插件市场找到了。

- pdf 导出的事，你可以直接用 pandoc 试试，如果不理想可以写 lua 脚本，进行处理。

lua 脚本，可以参考这个仓库的 lua 目录，目前实现的功能是导出的时候，连带图片一起导出了。如果搞定了，欢迎把 导出的命令提交给我😁。

https://github.com/mokeyish/obsidian-enhancing-export/blob/cfb82d85dee44f059ef5781ed1eafb20ac3ab72f/src/settings.ts#L118

**Comment by mokeyish** [comment]
这个就是利用 lua 进行自定义转换的，可以导出到 hugo https://gohugo.io/ 生成博客网站。
https://github.com/mokeyish/obsidian-enhancing-export/blob/cfb82d85dee44f059ef5781ed1eafb20ac3ab72f/src/settings.ts#L105-L110

**Comment by chenxin0397** [comment]
完全不懂lua是什么，怎么用

**Comment by mokeyish** [comment]
也许你可以参考这个

https://gowa.club/macOS/pandoc从markdown到pdf与docx全过程.html

**Comment by CharMingF** [comment]
> * 插件今天刚提交给官方，他们合并就能在插件市场找到了。
> * pdf 导出的事，你可以直接用 pandoc 试试，如果不理想可以写 lua 脚本，进行处理。
> 
> lua 脚本，可以参考这个仓库的 lua 目录，目前实现的功能是导出的时候，连带图片一起导出了。如果搞定了，欢迎把 导出的命令提交给我😁。
> 
> https://github.com/mokeyish/obsidian-enhancing-export/blob/cfb82d85dee44f059ef5781ed1eafb20ac3ab72f/src/settings.ts#L118-L123

我的理解是这个是不是需要ob的接口，他问的问题大概意思就是导出的是markdown格式的源文件，而他想要的是ob预览时候的版本，比如说一些ob特殊的语法，如块引用`![[dddd]]`在导出后应该显示对应引用的内容，但是却显示的是`![[dddd]]`

**Comment by mokeyish** [comment]
> 我的理解是这个是不是需要ob的接口，他问的问题大概意思就是导出的是markdown格式的源文件，而他想要的是ob预览时候的版本，比如说一些ob特殊的语法，如块引用`![[dddd]]`在导出后应该显示对应引用的内容，但是却显示的是`![[dddd]]`


他好像没说这个吧，你说的这个![[]]，建议使用标准的 markdown 语法(obsidian 上配置一下)，pandoc 不认识的，我也没做处理。这个导出没用到 ob 的接口，全是基于 pandoc 命令 + lua 微调的。

**Comment by chenxin0397** [comment]
还是感觉有些复杂，我一般都用typora实现pandoc的转换，但OB插件或CSS效果就没有了，您给的方法里有没有简单点的操作？感觉门坎还是有点高，要装的东西很多，但很多操作都看不懂
