### ISSUE TITLE
pandoc: xelatex: createProcess: posix_spawnp: illegal operation (Inappropriate ioctl for device)

### ISSUE THREAD

**Issue by apotenza92** [mokeyish/obsidian-enhancing-export#10]
Hi, I'm on macOS and receive this error. I'm using Pandoc and MacTex, both are installed and on my path but I still recieve this error.

<img width="749" alt="Screen Shot 2022-06-12 at 1 42 29 pm" src="https://user-images.githubusercontent.com/53612685/173213439-9deadbc7-0cb2-42e4-8a1e-65774efcf755.png">

I use the exact same command arguments on my PC using Pandoc and MikTEX and it works perfectly fine.

Is there something unique I need to do on macOS to ensure the installation of pandoc or Tex works?

**Comment by apotenza92** [comment]
Here are some terminal outputs to show you my install and the fact that everything is in my PATH. I've tried using both homebrew and manually installing pandoc and tex.

`which xelatex`
`/Library/TeX/texbin/xelatex`

`which pandoc`
`/usr/local/bin/pandoc`

`echo "${PATH//:/\n}"`
`/opt/homebrew/bin`
`/opt/homebrew/sbin`
`/usr/local/bin`
`/System/Cryptexes/App/usr/bin`
`/usr/bin`
`/bin`
`/usr/sbin`
`/sbin`
`/Library/TeX/texbin`

**Comment by mokeyish** [comment]
@apotenza92 Hi, did you run the command on terminal directly success? I have never use MikTEX，maybe should custom your own command.

**Comment by apotenza92** [comment]
I made a custom command that works perfectly well on Windows:
`pandoc --pdf-engine lualatex --resource-path="${currentDir}" --resource-path="${attachmentFolderPath}" -o "${outputDir}/${currentFileName}.pdf" "${currentPath}"`

That exact command doesn't work on Mac and you end up with the same error:
`pandoc: lualatex: createProcess: posix_spawnp: illegal operation (Inappropriate ioctl for device)`

If I run the command below in a Mac terminal it works perfectly:
`pandoc --pdf-engine lualatex -o "filename.pdf" "filename.md"`

I'm running these from a OneDrive folder by the way, I'm starting to suspect there might be something going wrong with the Mac accessing those folders so I'm doing some more experiments on whether this works if the files are just stored locally.

**Comment by apotenza92** [comment]
Sorry didn't mean to close.

**Comment by mokeyish** [comment]
@apotenza92 you look https://github.com/jgm/pandoc/issues/7570

**Comment by mokeyish** [comment]
Haven't seen this before, but I've seen a slightly different issue on M1 macs solved by specifying the **full path** to the pdflatex program.
```
pandoc -o my.pdf --pdf-engine=/Library/TeX/texbin/pdflatex
```
See pandoc FAQs.

_Originally posted by @jgm in https://github.com/jgm/pandoc/issues/7570#issuecomment-920319337_

**Comment by mokeyish** [comment]
> Here are some terminal outputs to show you my install and the fact that everything is in my PATH. I've tried using both homebrew and manually installing pandoc and tex.
> 
> `which xelatex` `/Library/TeX/texbin/xelatex`
> 
> `which pandoc` `/usr/local/bin/pandoc`
> 
> `echo "${PATH//:/\n}"` `/opt/homebrew/bin` `/opt/homebrew/sbin` `/usr/local/bin` `/System/Cryptexes/App/usr/bin` `/usr/bin` `/bin` `/usr/sbin` `/sbin` `/Library/TeX/texbin`

https://github.com/mokeyish/obsidian-enhancing-export/blob/00c21c350cfe7266cc3dbe4bbf933bb7ae16fb41/src/exporto0o.ts#L91-L95

You can specify the full path of lualatex， since there aren't extra paths in `PATH`, So I add `brewBin` manully in above code.

or make a symbolic of xelatex to `/usr/local/bin`
```shell
ln -s `which xelatex` /usr/local/bin
```

**Comment by mokeyish** [comment]
@apotenza92 Hi，Does the above solution work? if it works, I will add `/Library/TeX/texbin/` to the PATH

**Comment by rodzam** [comment]
> if it works, I will add `/Library/TeX/texbin/` to the PATH

@mokeyish Could you please add that PATH modification?

I'm on an M1 Mac and had a similar error message when I did not specify the full path to `xelatex` (in my case). When I manually supplied the full path in the extra argument (`--pdf-engine="/Library/TeX/texbin/xelatex"`), it was seemingly able to find `xelatex`. However, I would then get an error that `extractbb` could not be found. Curiously, when I executed the exact same command in my terminal, it worked.

Creating a symlink to `extractbb` in `/usr/local/bin` per your suggestion did the trick, which suggests to me that `/Library/TeX/texbin` is not being evaluated without your proposed fix and that specifying the full path in the argument is an insufficient solution for some use cases.

Thanks for your work on this excellent plugin!

**Comment by mokeyish** [comment]
Great, that's it's OK to add environment variables.  I'll add it later this week. Thank you for trying the above.

BTW: I'm writing another plugin [Code emitter](https://github.com/mokeyish/obsidian-code-emitter)
I hope it will be also useful to you.

**Comment by rodzam** [comment]
The new version works great! Obsidian no longer complains about the missing `extractbb` executable when I specify the full path to `xelatex` in the `--pdf-engine` argument. Furthermore, it is able to find `xelatex` without my specifying the full path. Thus, the program now behaves as expected.

I expect this would fix the original "illegal operation" issue that @apotenza92 experienced, too.

Thanks for the quick fix!
