### ISSUE TITLE
Export button dows not respond

### ISSUE THREAD

**Issue by bugrabirgili** [mokeyish/obsidian-enhancing-export#102]
Hi,

I've been trying to use your plugin to export my Obsidian document into a .docx file. I've not only tried Word (.docx) in the Type drop-down menu under the "Export to PDF" pop-up of your plugin but also I've tried other document types, as well. However, the Export button on the pop-up of your plugin does not respond. I've tried re-installing the plugin, but it didn't solve the problem.  Can you please assist me?

**Comment by mokeyish** [comment]
Do you have pandoc installed?

**Comment by bugrabirgili** [comment]
Yes it's also installed and it works correctly. The reason for my switching to your plugin is that I struggled to make live citations with standard obsidian-pandoc plugin si I wanted to follow your workflow (I've found your plugin through your blogpost)

**Comment by mokeyish** [comment]
I can't reproduce resetting your config.  The built-in export types will indeed be restored automatically.

**Comment by fruchtblase** [comment]
I had the same problem and aparrently it was caused by the YAML in my document (mixed tabs and spaces).

**Comment by mokeyish** [comment]
Bad YAML should be skipped. Can you put your YAML here?

**Comment by fruchtblase** [comment]
Here is an example document to reproduce the issue
[test2.md](https://github.com/mokeyish/obsidian-enhancing-export/files/12647557/test2.md)
