### ISSUE TITLE
Fails on loading image into pdf export

### ISSUE THREAD

**Issue by Nempickaxe** [mokeyish/obsidian-enhancing-export#107]
I've converted links to markdown and added --resource-path ~/Documents/GitHub/promo_notes/promo_notes/assets in extra arguments where all my jpgs are saved at. Yet it fails to export and throws this error

<img width="545" alt="Screenshot 2023-07-22 at 5 10 35 PM" src="https://github.com/mokeyish/obsidian-enhancing-export/assets/31272998/5b2e3318-5c37-4610-821d-009c0c66d6b5">

**Comment by mokeyish** [comment]
It should be an issue with pandoc's support for latex.
