### ISSUE TITLE
Extra arguments not sticking

### ISSUE THREAD

**Issue by wjfeeney** [mokeyish/obsidian-enhancing-export#108]
Frequently, my Extra arguments in settings for both PDF and Word(.docx) vanish, and (1) the only PDF argument is the default ```--pdf-engine=pdflatex```, and (2) the Word(.docx) arguments are gone, nothing is in the container. How do I fix this, so my settings stick?

**Comment by mokeyish** [comment]
This is the default, docx has no extra arguments.

https://github.com/mokeyish/obsidian-enhancing-export/blob/63cd903fdd955ef780ff48a3223b11d8917a188b/src/export_templates.ts#L57-L79

**Comment by wjfeeney** [comment]
I am aware of your default arguments. It is the Extra arguments that I created and inserted into the Extra arguments container—for PDF and Word(docx.)—that are disappearing after I insert them into the containers you provide for Extra arguments. 

The Extra arguments that I create and insert into the Extra arguments container work as expected. Then, a day or two later, these Extra arguments disappear from the Extra arguments containers. I have to reinsert the arguments again and again. Settings should not disappear. 

Hopefully, you will tell me how to fix this, so I don’t have to repeatedly reset the Extra Arguments settings. 

Thank you.

**Comment by mokeyish** [comment]
This is very strange!  It may be that the modification is too fast, and the time interval between the two modifications is very short?  Did you open its settings while it was resetting?

**Comment by mokeyish** [comment]
https://github.com/mokeyish/obsidian-enhancing-export/blob/63cd903fdd955ef780ff48a3223b11d8917a188b/src/main.ts#L97

There might be a bug here, but I'm not sure.  This configuration persistence will only write the part changed by the user to the hard disk. This is done so that when there is a direct modification of the default configuration in the code, the adjustment can take effect in time.

**Comment by wjfeeney** [comment]
Thanks for helping here. I did not open the settings while it was resetting. I am able to export a file correctly after inserting Extra arguments, and closing the settings interface. It all works for a while. I discover the missing Extra arguments when I attempt to export a subsequent file sometimes hours or even days later, and see the output file is inconsistent with the arguments. I'll will then open the settings interface and find the Extra arguments have disappeared! I then re-enter the settings, and history repeats itself.

**Comment by charveey** [comment]
I have the same issue

**Comment by mokeyish** [comment]
Hello, would you kindly test if it fixed?

**Comment by wjfeeney** [comment]
@mokeyish - I will monitor the settings for a while, and advise.

**Comment by universvm** [comment]
Noticed the same thing last week. It seems as though this is resolved with the latest update.

**Comment by wjfeeney** [comment]
I think this is fixed; my extra arguments are sticking. Thank you!
