### ISSUE TITLE
pandoc could not fetch resource

### ISSUE THREAD

**Issue by laycher** [mokeyish/obsidian-enhancing-export#109]
感谢作者的插件，但是在导出的时候发现 如果md文件的图片路径 是 /的话，导出的时候就会报错 could not fetch resource之类的，如果把 / 全部换成 \，是可以正常导出，但是在obsidian中图片是显示不出来的。
请问下，这块有什么好办法不？

**Comment by mokeyish** [comment]
统一采用相对距离，你应该是用了固定的路径了，obadian 会搜索它的附件目录，但是你用 typro 打开，应该也是找不到图片的。

**Comment by laycher** [comment]
用的是相对路径，只是路径中 用的是 / ，而不是\ ，全部换成 \ 后是可以正常导出的。

**Comment by mokeyish** [comment]
打开开发者工具，把生成的命令，分别拿出来看看，有什么区别。可能是转义的问题。不过我这边全都是使用 `/` 没见有问题
