### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by zenminimalist** [mokeyish/obsidian-enhancing-export#11]
Any way to include the textbundle export format in this Obsidian plugin?

**Comment by mokeyish** [comment]
I know few about textbundle. just a folder inlcuding files like this?

![图片](https://user-images.githubusercontent.com/16131917/177064715-6e166411-c0db-4136-8532-6db2fe987cc5.png)

**Comment by zenminimalist** [comment]
Yes, that's basically it. Essentially it's just a folder and has the assets in a separate folder.

**Comment by mokeyish** [comment]
It should be easy to implement it, just rename the media_dir 
https://github.com/mokeyish/obsidian-enhancing-export/blob/00c21c350cfe7266cc3dbe4bbf933bb7ae16fb41/lua/markdown.lua#L26

then put content into a folder .

**Comment by mokeyish** [comment]
The feature `textbundle export format` have been implemented. Please reopen if your have any questions about this.
