### ISSUE TITLE
currentDir becomes unintended when specific multibyte characters are included in the path name.

### ISSUE THREAD

**Issue by ryuzee** [mokeyish/obsidian-enhancing-export#111]
Thank you for the excellent plugin.
I use this plugin in a Japanese environment, but when the path contains certain multibyte characters, the value of `currentDir` becomes unintended. (See the screenshot below)

---
<img width="600" alt="image" src="https://github.com/mokeyish/obsidian-enhancing-export/assets/272013/e6e8d83a-c3d6-4b60-aa36-304dcc027a20">

---

in this case, I created `再現が確認できるテストドキュメント.md` under `テスト` directory. But the value of `currentDir` does not equal to `テスト`

The problem did not occur when I modified line 64 of exporto0o.ts as follows. However, I'm not sure if that's the correct way to fix it.

```
// const currentDir = currentPath.substring(0, currentPath.length - currentFile.name.length - 1);
const currentDir = path.dirname(currentPath)
```

**Comment by mokeyish** [comment]
Thanks! would you like to make a PR?
