### ISSUE TITLE
Redundant options specified in default export commands (PDF)

### ISSUE THREAD

**Issue by FeralFlora** [mokeyish/obsidian-enhancing-export#115]
1. One of the following two options is redundant in the default PDF export command:

    `--standalone -s`

    These both mean the same thing, so only one should be used.

2.  `--embed-resources`

    This is not applicable to PDFs, only HTML output. See [the docs](https://pandoc.org/MANUAL.html#options-affecting-specific-writers) on "Options affecting *specific* writers":
    >This option works only with HTML output formats, including html4, html5, html+lhs, html5+lhs, s5, slidy, slideous, dzslides, and revealjs.

**Comment by mokeyish** [comment]
Thanks for letting me know, it would be even better if you would like to submit a PR.
