### ISSUE TITLE
Default export settings revert to auto as soon as you close the settings popup

### ISSUE THREAD

**Issue by FeralFlora** [mokeyish/obsidian-enhancing-export#116]
As soon as I close the Export settings popup box, the Default Folder for Exported File setting reverts to `auto`, no matter what the option was set to previously.

Also, it's unclear what auto even means.

**Comment by maxtdaddy** [comment]
I have the same issue.  To be clear, it reverts to Auto, although it does still display below the custom Default Path I previously selected.
