### ISSUE TITLE
[FR] Remove the loading screen that blocks Obsidian while exporting

### ISSUE THREAD

**Issue by FeralFlora** [mokeyish/obsidian-enhancing-export#117]
One of the main reasons I still keep the Pandoc plugin around is that it simply exports in the background. When using Enhancing export, a loading screen prevents me from using Obsidian while an export is ongoing. This can take a while sometimes, especially when the tex distribution needs to install some packages to compile the document. I don't see why this loading screen is necessary?

**Comment by mokeyish** [comment]
My export speed is very fast. How long did it take you?

**Comment by FeralFlora** [comment]
> My export speed is very fast. How long did it take you?

It takes a long time if you, for example, change the font family with:

```
---
fontfamily: noto
---
```

If it's the first time using the font, this will make the tex distribution (MikTex in my case) download several packages. This extends the export time by a lot.

I may also have a slower computer than you. But I think the plugin shouldn't assume that everyone has equally fast computers.

Regardless of export time, the point is that I don't see the value in a full loading screen. And in the case of long exports, it is very inconvenient.

**Comment by universvm** [comment]
It takes a long time especially if you have a big document or images. Overall there is no reason for the loading screen to hide the notes.

My current workaround is to open the document in a new window and run the plugin while I continue to edit other notes

**Comment by mokeyish** [comment]
Is this okay?

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/16131917/9469b73f-a64f-49eb-8f34-460364d4113d)

**Comment by FeralFlora** [comment]
@mokeyish That would be great for me, so long as there is still some notice that gives information about the export.

**Comment by mokeyish** [comment]
https://github.com/mokeyish/obsidian-enhancing-export/commit/e351ff2864ef3f965166dfafa6da7e6776e8565b

**Comment by FeralFlora** [comment]
> https://github.com/mokeyish/obsidian-enhancing-export/commit/e351ff2864ef3f965166dfafa6da7e6776e8565b

Did you want a comment on this or for me to test it?

**Comment by mokeyish** [comment]
Yeah, you can test it.

**Comment by FeralFlora** [comment]
> Yeah, you can test it.

I just tested the new release, and it seems to be working well. Thanks!
