### ISSUE TITLE
不管什么格式都导出失败

### ISSUE THREAD

**Issue by human7** [mokeyish/obsidian-enhancing-export#118]
各位大佬好，我使用该插件各种格式都无法导出，最后还有乱码显示。
![issues-enhancing-export](https://github.com/mokeyish/obsidian-enhancing-export/assets/10898373/e272166d-1752-490e-991c-f4a57124d165)

环境：
- obsidian v1.1.16
- pandoc 3.1.6.1, 安装路径：d:\Program Files\Pandoc\pandoc.exe

使用其他插件例如：`pandoc plugin`调用pandoc导出docx，html等文件都没有问题，唯独该插件无法导出，请大佬解惑，谢谢

**Comment by Qunter** [comment]
+1

**Comment by mokeyish** [comment]
无法重现。pdf 导出需要额外配置 pdf engine，你检查下路径，两者生成的命令区别，环境变量的区别。

**Comment by human7** [comment]
> 无法重现。pdf 导出需要额外配置 pdf engine，你检查下路径，两者生成的命令区别，环境变量的区别。

请问 pdf Engine 如何配置

**Comment by mokeyish** [comment]
> ![image](https://user-images.githubusercontent.com/144794808/269253781-2a8ee28c-c300-4449-9b53-3153c7c44644.png)

升级最新 pandoc 版本

**Comment by mokeyish** [comment]
可能是这个原因 https://github.com/mokeyish/obsidian-enhancing-export/issues/9

**Comment by mokeyish** [comment]
> > 无法重现。pdf 导出需要额外配置 pdf engine，你检查下路径，两者生成的命令区别，环境变量的区别。
> 
> 请问 pdf Engine 如何配置

https://pandoc.org/MANUAL.html#creating-a-pdf

**Comment by mokeyish** [comment]
@human7 只是 pdf 吗？

**Comment by czcn** [comment]
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/29677536/d2957bd5-8cc5-4b50-a300-8c09f7e847e8) 同样的问题，怎么解？

**Comment by mokeyish** [comment]
先不用这个插件，直接用 pandoc 命令看看。这个工具只是生成导出命令而已。

**Comment by Alleyf** [comment]
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/94681151/f734bf99-539c-4dc7-9393-1383c21b6d21)
我也是什么都导出不了，环境变量也配置了

**Comment by Ruach-yi** [comment]
我也遇到了类似的情况，尝试更改安pandoc安装路径后导出成功，怀疑是安装路径中包含空格导致的。例如你的路径“d:\Program Files”中包含了一个空格，本楼的其他朋友可能也有类似情况。

**Comment by Alleyf** [comment]
> 我也遇到了类似的情况，尝试更改安pandoc安装路径后导出成功，怀疑是安装路径中包含空格导致的。例如你的路径“d:\Program Files”中包含了一个空格，本楼的其他朋友可能也有类似情况。

yes，i did it successfully！

**Comment by mokeyish** [comment]
那这个问题应该是可以修复的。

**Comment by mokeyish** [comment]
> 我也遇到了类似的情况，尝试更改安pandoc安装路径后导出成功，怀疑是安装路径中包含空格导致的。例如你的路径“d:\Program Files”中包含了一个空格，本楼的其他朋友可能也有类似情况。

@Ruach-yi 感谢你的排查出问题的原因，已经修复了。


大家可以再试试。
