### ISSUE TITLE
Generating does not lead to output file

### ISSUE THREAD

**Issue by universvm** [mokeyish/obsidian-enhancing-export#12]
Hi, 

I'm trying the plugin. It used to work until this morning when I updated and  tried to export literally any file. 

It just keeps saying "generating" on any file. 

Can you replicate this?

**Comment by universvm** [comment]
This happens on any extensions.

**Comment by mokeyish** [comment]
What's your os ?

**Comment by universvm** [comment]
Macos
<img width="595" alt="Screenshot 2022-07-05 at 18 06 19" src="https://user-images.githubusercontent.com/17524568/177380146-a64540c7-f0d7-49d6-a942-67c70033f0e1.png">
 
For context, I'm able to use other pandoc plugins (although I prefer this one) and pandoc works from the command line. No additional arguments were added.

**Comment by universvm** [comment]
Found the issue. It's related to having spaces in the filename.
[Sample 1.md](https://github.com/mokeyish/obsidian-enhancing-export/files/9048242/Sample.1.md)

If you remove the space it will output a file.

**Comment by mokeyish** [comment]
Thanks for reporting, I have fix it. please update to the latest version.
