### ISSUE TITLE
自定义模板

### ISSUE THREAD

**Issue by Arionbat** [mokeyish/obsidian-enhancing-export#120]
# 自定义模板优化
插件中 预置模板位置 在 ${pluginDir}/textemplate,代码中模板选项是固定的，能否将这部分的逻辑修改成扫描该路径下的.tex和.latex 的形式，这样的话，模板选择的灵活性会比较高，希望可以考虑下该提议

**Comment by Arionbat** [comment]
忘记ts 无法扫描磁盘文件了，抱歉

**Comment by mokeyish** [comment]
可以扫描磁盘的，用 nodejs 接口。
