### ISSUE TITLE
obsidian 导出为 epub 格式时无法显示图片

### ISSUE THREAD

**Issue by pzponge** [mokeyish/obsidian-enhancing-export#121]
我的图片素材是放在另外一个文件夹中的，没有和 markdown 文档放在同一文件夹下。导出 epub 格式后，图片部分依然显示的是：

![[999-笔记素材/202309192114/01.jpeg]]

而不是图片。

不知道应该如何设置？谢谢

**Comment by mokeyish** [comment]
不支持 wikilink 格式，仅支持标准 markdown 语法，我是把 wikilinks 关了的，因为写笔记还是用 typora 写，用着更舒适，Ovsidian 仅用来管理笔记。

**Comment by pzponge** [comment]
> 不支持 wikilink 格式，仅支持标准 markdown 语法，我是把 wikilinks 关了的，因为写笔记还是用 typora 写，用着更舒适，Ovsidian 仅用来管理笔记。

了解了，感谢
