### ISSUE TITLE
导出为HTML文件时没带图片等资源，且不勾选覆盖文件的话会卡在导出过程中

### ISSUE THREAD

**Issue by YandLiu** [mokeyish/obsidian-enhancing-export#123]

**Comment by mokeyish** [comment]
wikilinks 是不支持的。用标准的 markdown 语法。

**Comment by YandLiu** [comment]
用标准的MD语法可以看到导出网页里的图片了
不过如果勾选覆盖文件确认的话还是会卡在导出过程，只能强关掉程序

**Comment by mokeyish** [comment]
> 用标准的MD语法可以看到导出网页里的图片了 不过如果勾选覆盖文件确认的话还是会卡在导出过程，只能强关掉程序

嗯，我也重现了，修复一下

**Comment by mokeyish** [comment]
如果你需要 Wikilinks 你可以看看这个 issue #74 ，pandoc 貌似已经通过插件支持了，只不过我自己没用，也就没去测试了。
