### ISSUE TITLE
导出word时所有嵌入的内容都仅以文字显示呈现

### ISSUE THREAD

**Issue by wwjCMP** [mokeyish/obsidian-enhancing-export#128]
比如嵌入的文章
![[dfdfs]]

比如嵌入的图片
![[A1-附件/sjfjofpgw.png]]

**Comment by mokeyish** [comment]
不支持 wikilinks，用标准的 markdown 语法

**Comment by TimFruit** [comment]
主要看这个 https://github.com/mokeyish/obsidian-enhancing-export/issues/74


下面这个方面一点，但也不是很好，会出现图片路径

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/23203575/438d698b-d4e0-4cc2-92f9-0703a96759b6)

**Comment by TimFruit** [comment]
主要看这个 https://github.com/mokeyish/obsidian-enhancing-export/issues/74

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/23203575/bd36e053-e476-42fb-bc1f-91d32fd5c8a4)


通过lua脚本我现在可以了




```
function Pandoc(doc)
  -- 遍历文档中的所有块元素
  for i, block in pairs(doc.blocks) do
    if block.t == 'Para' then
      -- 在段落文本中进行替换
      doc.blocks[i] = pandoc.Para(replace_wikilinks(block.content))
    end
  end
  return doc
end

function replace_wikilinks(content)
  local new_content = {}
  local text = pandoc.utils.stringify(content)

  -- 使用正则表达式匹配文本中的 Wikilink 格式
  text = text:gsub("!(%[%[[^%]]*%]%])", function(link)
    local img_path = link:match("%[%[([^%]]*)%]%]")
    return "![](" .. img_path .. ")"
  end)

  return pandoc.read(text).blocks[1].content
end

return { { Pandoc = Pandoc } }

```

**Comment by mokeyish** [comment]
#154
