### ISSUE TITLE
Support Jira export

### ISSUE THREAD

**Issue by macintacos** [mokeyish/obsidian-enhancing-export#129]
Pandoc [support's Jira formatting](https://pandoc.org/MANUAL.html#:~:text=(JATS%20XML)-,jira,-(Jira/Confluence). Any chance that could be added to the tool?

**Comment by mokeyish** [comment]
You can try it directly on the command line terminal, and then you can add custom commands in the settings interface of this tool, or submit a PR to this repository as the default installation export type

**Comment by macintacos** [comment]
Got around to doing this, figured I might as well share what I came up with before closing this out.

1. Go to "Export Settings".
2. Click the "+" next to the "Choose template" dropdown.
3. In the "Template" dropdown, click "Custom" and then set the "Name" field to "Jira".
4. Choose "Jira" in the "Choose template" dropdown.
5. In the "Command" field, add the following:

```
pandoc -f ${fromFormat} --resource-path="${currentDir}" --resource-path="${attachmentFolderPath}" -s -o "${outputPath}" -t jira "${currentFileFullName}"
```

After that, you can use the Enhancing Export command and choose "Jira" to export your markdown files to Jira. Seems to work pretty well!
