### ISSUE TITLE
不能正常导出图片

### ISSUE THREAD

**Issue by whitejava** [mokeyish/obsidian-enhancing-export#13]
导出前的代码是这样的：

``` md
![[assets/test.png]]
```

导出HTML之后并不是图片，而是这样的文本：

[[assets/test.png]]

**Comment by mokeyish** [comment]
`![[assets/test.png]]` 这种写法 obsidian 的，暂不支持了，建议图片用标准的 markdown 语法。

**Comment by whitejava** [comment]
好的，感谢大佬。我改成标准链接格式确实可以了。

**Comment by whitejava** [comment]
话说WikiLink格式兼容性太差了，Obsidian竟然默认开启。

**Comment by whitejava** [comment]
对了还有个问题是路径只能支持相对路径。如果用绝对路径的话pandoc会报错找不到文件。

这也是Obsidian的锅，我给设置了使用绝对路径。

所以我改成了相对路径就能正常导出图片了。

**Comment by mokeyish** [comment]
你可以用 typora 打开看看的，我一般用 typora 写的笔记，obsidian 是用来管理的。。用相对路径，标准 markdown 语法，两个 app 是可以互相兼容打开的。

**Comment by mokeyish** [comment]
marktext 也是可以的

**Comment by whitejava** [comment]
好的，由于电脑是Windows，我试试MarkText。感谢大佬！
