### ISSUE TITLE
Citations not rendering in export to PDF

### ISSUE THREAD

**Issue by jenniferpanitz** [mokeyish/obsidian-enhancing-export#137]
Hi there, I am trying to follow this [article](https://betterhumans.pub/obsidian-tutorial-for-academic-writing-87b038060522), especially steps 3B and 4A to export an Obsidian .md note into a PDF with the "Academic Paper" LaTeX template and rendered citations, i.e., citekeys in the .md note to be converted to formatted citations in the PDF. I got a related action, export to MS Word with formatted citations, to work using pandoc in terminal in case that is helpful.

I am on a MacBook running Big Sur Version 11.7.10. Zotero Version 6.0.30. Obsidian Version 1.4.16. Pandoc Version: pandoc 3.1.9, Features: +server +lua, Scripting engine: Lua 5.4

I have previously linked Zotero to Obsidian and installed BetterBibTex on Zotero to attach citekeys to all the references in my library. I can access my Zotero library in Obsidian and note down citekeys, which Obsidian then automatically converts to formatted references, e.g., citekey "@CiteKey_2023" and the reference would be "Cite & Key (2023)".

The plugin settings are the following:
![Screen Shot 2023-11-29 at 4 27 36 PM](https://github.com/mokeyish/obsidian-enhancing-export/assets/152407773/8b2b8b94-92bf-4ae9-b175-dad9f4cc88f7)

The Extra Arguments I am using are these:
--resource-path="[absolute path to folder where I keep all the referenced files, including the bibliography]"
--bibliography="PhD_library.yaml" 
--pdf-engine=/Library/TeX/texbin/pdflatex 
--number-sections 
--citeproc 
-M reference-section-title=References

The PDF doesn't render and I am shown the following error message
![Screen Shot 2023-11-29 at 4 31 49 PM](https://github.com/mokeyish/obsidian-enhancing-export/assets/152407773/72b9f0f4-6e90-4694-a4bb-8d7fe7e5dbea)

From trying to Google that it seems to point to a duplication within the extra arguments section that refers to the --bibliography argument and the --citeproc flag.

If I run with the below Extra Arguments (removed --citeproc), a PDF is rendered but it still includes the citekeys - the references have not been formatted.
--resource-path="[absolute path to folder where I keep all the referenced files, including the bibliography]"
--bibliography="PhD_library.yaml" 
--pdf-engine=/Library/TeX/texbin/pdflatex 
--number-sections 
-M reference-section-title=References

If I run with the below Extra Arguments (added --citeproc back in and removed --bibliography), I get a different error message that citations could not be found, see below.
--resource-path="[absolute path to folder where I keep all the referenced files, including the bibliography]"
--pdf-engine=/Library/TeX/texbin/pdflatex 
--number-sections 
--citeproc 
-M reference-section-title=References

![Screen Shot 2023-11-29 at 4 36 42 PM](https://github.com/mokeyish/obsidian-enhancing-export/assets/152407773/7c3f7c7c-f5ad-4fd4-ae6e-148941596218)

This of course makes sense as I have removed the path to the bibliography.

From testing things it seems to me like as discussed in the [article](https://betterhumans.pub/obsidian-tutorial-for-academic-writing-87b038060522), both the path to the bibliography and the citeproc flag are needed, but I don't understand the error Obsidian shows me when I include both in the Extra Arguments. I would be grateful for help in resolving this as I have stared at this for a couple of days now. Please let me know whether any more information is needed!

Thank you,
Jenny

**Comment by TheFermi0n** [comment]
Have you tried using the defaults template for exporting? If not then...

1. Open terminal and use the following code `pandoc  -D latex > ./defaults.tex`. This will generate the defaults template of pandoc.
2. Inside the file you can see that there is a section with 
    ```latex
    $if(csl-refs)$

    citeproc code here...

    $endif$
     ```
    If you are using your own template try adding this section to it or change to the defaults template.

To use the template just add `--template='path/defaults.tex'` in the `Arguments` field in the `Export Settings > Edit Command Template > Choose Template=PDF`

**Comment by TheFermi0n** [comment]
> Have you tried using the defaults template for exporting? If not then...
> 
> 1. Open terminal and use the following code `pandoc  -D latex > ./defaults.tex`. This will generate the defaults template of pandoc.
> 2. Inside the file you can see that there is a section with
>    ```
>    $if(csl-refs)$
>    
>    citeproc code here...
>    
>    $endif$
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    If you are using your own template try adding this section to it or change to the defaults template.
> 
> To use the template just add `--template='path/defaults.tex'` in the `Arguments` field in the `Export Settings > Edit Command Template > Choose Template=PDF`

PS. I am not sure if this will work. But, I too faced citeproc issues while using my own template without the mentioned code.

**Comment by jenniferpanitz** [comment]
That solved it! Thanks so much :)
