### ISSUE TITLE
Cannot auto-detect pandoc in macos

### ISSUE THREAD

**Issue by chuyaowang** [mokeyish/obsidian-enhancing-export#140]
The plugin is unable to read the pandoc path from the $PATH variable on macos. I am using the plugin on macos 13.5. 

I have installed pandoc with homebrew: 
```
brew install pandoc
brew install librsvg homebrew/cask/basictex
```
The path is `/opt/homebrew/bin/pandoc`. When I add this path in the settings of the plugin, it finds pandoc no problem, but when I modify the $PATH variable in `/etc/paths`, the plugin cannot auto-detect pandoc. The path is indeed added as when I enter `echo $PATH`, I can see the newly added path in the output.

**Comment by mokeyish** [comment]
/opt/homebrew is not in the preset path environment variables.

https://github.com/mokeyish/obsidian-enhancing-export/blob/7961cfa290ff57932488769b4945df714e6aac8f/src/settings.ts#L127

You can add it manually.

**Comment by LYTWilson** [comment]
> /opt/homebrew is not in the preset path environment variables.
> 
> https://github.com/mokeyish/obsidian-enhancing-export/blob/7961cfa290ff57932488769b4945df714e6aac8f/src/settings.ts#L127
> 
> You can add it manually.

Hello! Thanks for the help! But I am not a coder, I installed pandoc via home-brew with tutorials, but how might I do to add that home-brew bin? Should I configure some settings in my obsidian plugin config?

**Comment by mokeyish** [comment]
> Hello! Thanks for the help! But I am not a coder, I installed pandoc via home-brew with tutorials, but how might I do to add that home-brew bin? Should I configure some settings in my obsidian plugin config?

Please set it at settings tab.

**Comment by mokeyish** [comment]
I've fix it, please try the latest version.
