### ISSUE TITLE
Total crash of archlinux system  when doing it wrong! .odt > .md NO NO!

### ISSUE THREAD

**Issue by Jirido** [mokeyish/obsidian-enhancing-export#144]
I run an updated archlinux system with pandoc-cli 0.1.1.1-26 installed
After having chosen an docx file and export to  markdown the progress indicator shows. Then it goes on until all memory is consumed and the system is going down. Even thou I started obsidian in cli I see no errors. After having terminated obsidian with ctl+c the system still crash. so it seam to be pandoc that take it down. Maybe the problem is that it can't handle converting to markdown from docx with the settings your plugin provide. But it would be sweet if it could.
Also to be able to choose export to copy or export and remove original would be sweet.

**Comment by mokeyish** [comment]
please install latest pandoc.

**Comment by Jirido** [comment]
I did install it and tried. The result is the same. It hangs and crash my system.
:) pandoc -v
pandoc 3.1.11
Features: +server +lua
Scripting engine: Lua 5.4

Should it be able to convert .docx files to markdown in your plugin?

**Comment by mokeyish** [comment]
No, it only supports converting from markdown.

**Comment by Jirido** [comment]
O that's why it don't work. It would be very good to be able to convert to .md from .pdf, .html, .rtf, .odt and .docx. 
Many people in our association use and share google and work in docx. Others edit on libreoffice and I like to use obsidian and markdown. And like to export also to grav(flat file cms).  I would love to be able to import to .md trough pandocs that have the capability. I then could edit and export as it is necessary. Would this be be hard for you to implement? I can alfa test for you if you do :)

**Comment by Jirido** [comment]
I guess this don't help at all, but I found it a bit interesting. It could be cool with a obsidian plugin that converted different files that Were dropped in to a folder to obsidian markdown notes. https://nextpertise.net/posts/230509_word2obsidian/

**Comment by Jirido** [comment]
Also i had to manually install texlive-latex and texlive-fontsrecommended to get pandoc to make pdf. 
I find the pdfs to have a bit large marginals.
