### ISSUE TITLE
Even though PDFLatex is installed, Plugin insists that it is not installed.

### ISSUE THREAD

**Issue by WinnerWind** [mokeyish/obsidian-enhancing-export#145]
I installed PDFLatex using pip `pip install pdflatex` and CMD says that PDFLatex is already installed (Python 3.12)
However, I keep getting this error saying that PDFLatex is not installed.
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/71366717/5204f25a-733b-4168-8dc1-dc382cfd7bb9)
How do I fix this?

**Comment by Jirido** [comment]
I had it also on linux but had to install texlive-latex and texlive-fontsrecommended. I don't know what they are named on WDos

**Comment by mokeyish** [comment]
Please set the PATH environment varables in the settings of this plugin.

**Comment by WinnerWind** [comment]
I ended up installing Texworks and now it works like a dream. The PIP version of PDFLatex is insufficient. Try installing MIKLatex or Latexlive.
