### ISSUE TITLE
Feature Request: Add the function to convert from different formats to markdown. 🍁

### ISSUE THREAD

**Issue by Jirido** [mokeyish/obsidian-enhancing-export#146]
It would be very good to be able to convert to .md from .pdf, .html, .rtf, .odt and .docx.
Many people in our association use and share google docx and work in docx or odt on libreoffice. I like to use obsidian and markdown. And I also like to export markdown to grav(flat file cms). 

I would love ❤️ to be able to import different file formats in to .md trough pandocs. 
 I then could edit and export as it is necessary. 
 
 Would this be be hard for you to implement? I can alfa test for you if you do :)

For now i use this solution to drop in files in sertain odt@md, docx@md folders to get them automatically converted to .md
https://nextpertise.net/posts/230509_word2obsidian/   a 👻 shell, pandoc, inotify solution 🌴
It could also be cool with a obsidian plugin that converted different files that Were dropped in to a folder to obsidian markdown notes.

**Comment by mokeyish** [comment]
Obsidian mainly uses markdown, and currently there is no energy or plan to develop and convert from other formats to markdown.

**Comment by Jirido** [comment]
Ok I see. 
Well thanks for your work on a good and useful plugin.  👍️ 🐬
