### ISSUE TITLE
Linking files does not work, and leaves the text as it is verbatim.

### ISSUE THREAD

**Issue by WinnerWind** [mokeyish/obsidian-enhancing-export#149]
Linking files as done below in  the screenshot 
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/71366717/8a6aa928-304e-47a0-8989-fe2cd91164ab)
Leaves the output visible in all preset formats including None
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/71366717/d62fd3c7-7be3-43c7-86da-d376a727128c)
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/71366717/1c8bc9a1-5c06-4564-a437-9b502107abf3)
However, this is not an issue with the inbuilt PDF exporter. It's not an issue, in the sense that it is highlighted but not a working link
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/71366717/4412fc87-3b4f-4bbd-a4ee-b9451e3f9be9)

Would it be possible to add a case in the plugin code that automatically converts links into their link text, and/or remove the link formatting, making all the text look homogenous?

**Comment by mokeyish** [comment]
#154
