### ISSUE TITLE
导出PDF失败

### ISSUE THREAD

**Issue by ycbrd** [mokeyish/obsidian-enhancing-export#15]
同一个文件，导出docx是没有问题的，PDF报错。
![image](https://user-images.githubusercontent.com/105804326/184082114-2bef3f49-909d-41b3-85eb-fe760954b812.png)

**Comment by mokeyish** [comment]
基于 pandoc 的 PDF导出 要安装 pdf engine 的，有点麻烦，官方自带的 pdf 可以用的。。。如果文档中有 gif 动画，建议直接导出 html 单文件版

<img width="863" alt="图片" src="https://user-images.githubusercontent.com/16131917/184087980-c1b74456-79a6-4e68-96b3-c51f307e2b8f.png">

**Comment by ycbrd** [comment]
感谢您的回复和提醒。🌹
也谢谢您的插件。

**Comment by ycbrd** [comment]
> 基于 pandoc 的 PDF导出 要安装 pdf engine 的，有点麻烦，官方自带的 pdf 可以用的。。。如果文档中有 gif 动画，建议直接导出 html 单文件版

主要矛盾痛点是官方自带导出不含书签目录，想顺便咨询下如果pandoc配置了PDF engine可以带目录吗？如果用其他方法可以导出带目录的PDF吗？

**Comment by mokeyish** [comment]
我也没用过，你可以试试看，仔细看看 pandoc 文档，要加参数的加参，可能可以搞定的。。。如果搞定了，欢迎贡献你的命令模板到这 https://github.com/mokeyish/obsidian-enhancing-export/blob/master/src/export_command_templates.ts
