### ISSUE TITLE
Can't export markdown file with attachment

### ISSUE THREAD

**Issue by xjl456852** [mokeyish/obsidian-enhancing-export#150]
Can't export markdown file with attachment

The output dir does have  resources dir, it's didn't create the resources dir.
It only export the markdown file.

The parameter is
`
-f markdown  --resource-path="${vaultDir}" --resource-path="${currentDir}" --resource-path="${attachmentFolderPath}" --lua-filter="${luaDir}/markdown.lua"  -s -o "${outputPath}"  -t commonmark_x-attributes
`

Thank you

**Comment by xjl456852** [comment]
原来大家都是中国人啊.
导出中尝试了导出为markdown的三种方式Markdown, Markdown(hugo), TextBundle,都无法将附件图片导出
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/8008097/e297d358-7b21-4a79-92d6-d3e540e2cc6f)

使用TextBundle还报错
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/8008097/e84b8da3-7f05-4b6b-abef-97429d5f4615)

文件内容:
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/8008097/d72efd9e-e3d4-4934-93a0-4ef35ceb86bd)

文件和图片仓库的位置如下
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/8008097/872f55d1-fcec-4fa6-98c1-12d985e942f9)

现在无法直接导出带图片的文件

**Comment by brunoamaral** [comment]
I just had the same problem with a docx file. 

```
Command: /opt/homebrew/bin/pandoc -f markdown --resource-path="/Users/brunoamaral/Library/Mobile Documents/iCloud~md~obsidian/Documents/ExoCortex/Artigos/ESCS" --resource-path="Files" -s -o "/Users/brunoamaral/Downloads/IA nas Relações Públicas, da Estratégia de Comunicagao a geração de
output.docx" -t docx --citeproc --bibliography "/Users/brunoamaral/Documents/zotero-references.json" --csl
"/Users/brunoamaral/Zotero/styles/apa.csl"

"/Users/brunoamaral/Library/Mobile Documents/iCloud~md~obsidian/Documents/ExoCortex/Artigos/ESCS/IA nas Relações Públicas, da Estratégia de Comunicagao a geração de output.md", Error:[ WARNING] Could not fetch resource 53404929226 _b8343b5828_o0.jpg: replacing image with description
```

Aside from both me and @xjl456852 using different character sets, I noticed that the path to the `Files` vault where I keep the attachments is not an absolute path.

**Comment by mokeyish** [comment]
Please try to remove the spaces in the image path. This requires troubleshooting. Normally, there is no problem with exporting. I have tested it myself.

**Comment by mokeyish** [comment]
#157
