### ISSUE TITLE
Pandoc command contains backslashes

### ISSUE THREAD

**Issue by xarx00** [mokeyish/obsidian-enhancing-export#153]
I have just installed the plugin and Pandoc in Windows 10.

When I run the plugin "Export:Export to..." command, it starts Pandoc, but Pandoc freezes.
The reason is that Pandoc doesn't like backslashes in paths.

`pandoc  -f markdown --resource-path="C:\Temp\MyVault" --resource-path="C:\Temp\MyVault\" --lua-filter="C:\Temp\MyVault/.obsidian/plugins/obsidian-enhancing-export/lua/markdown.lua" -s -o "C:\Temp/ANote.md" -t commonmark_x-attributes  "C:\Temp\MyVault\ANote.md"
`
After changing all backslashes to slashes, the command executes correctly.

I propose to replace all backslashes with slashes in the command.

Environment:
Windows 10, Obsidian 1.5.3, Obsidian Enhancing Export 1.9.6.

**Comment by mokeyish** [comment]
Would you like to provide the command that you modified?

**Comment by mokeyish** [comment]
@xarx00 please try the latest version

**Comment by xarx00** [comment]
It works, thank you.
