### ISSUE TITLE
`Same folder with current file` option doesn't work as intended

### ISSUE THREAD

**Issue by jgenc** [mokeyish/obsidian-enhancing-export#159]
I was playing around with the extension and its capabilities and I noticed that the `Same folder with current file` value for the `Default Folder for Exported File` didn't work as I thought it would.

That behavior seemed weird to be and I decided to look at the source code.

I found the following:

- The `defaultExportDirectoryMode` field of `globalSetting` is only accessed in the `src/ui/legacy/export_dialog.ts` file in [line 44](https://github.com/mokeyish/obsidian-enhancing-export/blob/6a724e3b54ad077eba6c9fde27599a6787906242/src/ui/legacy/export_dialog.ts#L44)
   - I suppose that the legacy files are either not used anymore or are there to support the legacy mode of Obsidian
- In the non-legacy files there is no access to this field anymore, rendering any value of the `defaultExportDirectoryMode` (Auto, Same, Custom) useless

I figured that a good idea would be to add this variable check in the Export dialog file (`src/ui/ExportDialog.tsx`). In the case that the user decides to change the export path from the "Same folder" option it will correctly change the output. I did some testing and it didn't break/affect other modes of `Default Folder for Exported File`. I'd also like to note that I tested this on macOS 14.2.1.

I've made a fork [here](https://github.com/mokeyish/obsidian-enhancing-export/compare/main...jgenc:obsidian-enhancing-export:main). If you think it's fine, I can create a pull request. If not, I can just delete the fork and wait for the fix if you don't like the changes.

Thank you for the amazing plugin 🤗

**Comment by mokeyish** [comment]
Thanks for pointing it out, I think I forgot to migrate this code. You add `custom` as well.

**Comment by jgenc** [comment]
Oh yeah, my bad, I forgot to add the `custom` value too. Added it. Should I create the request now?

**Comment by mokeyish** [comment]
Yes, looking forward to your PR
