### ISSUE TITLE
MacOS export as Epub 

### ISSUE THREAD

**Issue by TransonQ** [mokeyish/obsidian-enhancing-export#164]
When I export the file as an epub format, I encountered this error.
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/68772719/2ecf3d07-990e-476f-9542-d0d50d6251d6)

Although there is this warning, the file has been exported successfully. Can the warning be removed?

**Comment by TransonQ** [comment]
I tried customizing commands in the settings and adding metadata properties such as the title, author name, and contact information, and that should do it.

```
-f ${fromFormat} --resource-path="${currentDir}" --resource-path="${attachmentFolderPath}" -s -o "${outputPath}" -t epub  --metadata title="BOOK_TITLE" --metadata author="YOUR_NAME" --metadata contact="CONTACT_INFO"
```

**Comment by mokeyish** [comment]
it would be better to add yaml metadta in the head of markdown.

**Comment by TransonQ** [comment]
> it would be better to add yaml metadta in the head of markdown.最好在markdown的头部添加yaml metadta。

thanks :)
