### ISSUE TITLE
Don't specify input file last, since it can cause unpredictable behaviours (overwriting input file)

### ISSUE THREAD

**Issue by FeralFlora** [mokeyish/obsidian-enhancing-export#166]
In `exporto0o.ts`, the input file is specified last, after all the arguments:

https://github.com/mokeyish/obsidian-enhancing-export/blob/36acb485bd1f4d4a882ab042f28bf8af1cfff71c/src/exporto0o.ts#L178

If the user for some reason leaves a `-o` with no path specified at the end of the argument list, then Pandoc will overwrite the input file - likely with incompatible text formatting (Word code in an .md file). If the user does not have backups, this could potentially be very bad.

Therefore, I suggest that the input file should be specified first, before the `-f` argument. This is also the conventional argument order, as presented in the "Getting started" page of Pandoc: https://pandoc.org/getting-started.html#step-6-converting-a-file

> To convert it to HTML, use this command:
> `pandoc test1.md -f markdown -t html -s -o test1.html`

**Comment by mokeyish** [comment]
Sounds great, would you like to submit a PR to update it?
