### ISSUE TITLE
no code syntax highlight for many formats

### ISSUE THREAD

**Issue by anutator** [mokeyish/obsidian-enhancing-export#168]
I try to export document from Obsidian to epub.
If I use bash code syntax — it is highlighted. If I use shell, nginx syntax for code blocks, it is not highligted.

Besides I tested export to pdf with Obsidian export (without plugins). It exports all code blocks as highlited.

Is it possible to use Obsidian theme to export to epub and save all syntax for code blocks?

The recent versions of Obsidian & obsidian-enhancing-export plugin.
pandoc 3.1.12.2

Linux (Pop!_OS)

**Comment by anutator** [comment]
I found that shell and nginx are not included in pandoc highlighted languages:

```
$ pandoc --list-highlight-languages
...
mustache
nasm
nim
nix
noweb
objectivec
...
rust
sass
scala
scheme
sci
scss
sed
sgml
sml
spdxcomments
sql
sqlmysql
sqlpostgresql
stan
stata
swift
systemverilog
tcl
...
```

**Comment by mokeyish** [comment]
This plugin is based on pandoc. Please ask the pandoc community.
