### ISSUE TITLE
Obsidian callouts not supported

### ISSUE THREAD

**Issue by sonnyding1** [mokeyish/obsidian-enhancing-export#169]
When I tried to export a note that used callouts, the export didn't recognize the callout blocks, and the exported PDF is unreadable. This also occurs when I tried to export as HTML.

Here is the link to Obsidian callouts: https://help.obsidian.md/Editing+and+formatting/Callouts

Thanks!

**Comment by mokeyish** [comment]
This plugin is based on pandoc. Please ask the pandoc community.

**Comment by sonnyding1** [comment]
Ok thank you!
