### ISSUE TITLE
Errors due to undefined `progress` cause all Obsidian hotkeys to become unresponsive until Obsidian restart

### ISSUE THREAD

**Issue by FeralFlora** [mokeyish/obsidian-enhancing-export#175]
As reported in #173, it seems like something changed in Obsidian's `loadProgress` API since version 1.6.0. Any reference to `progress` causes errors that prevent exports from working.

Another side effect of these errors is that **Obsidian hotkeys stop working**, until you restart Obsidian (https://github.com/mokeyish/obsidian-enhancing-export/issues/173#issuecomment-2106555966).

## Steps to reproduce

1a. Run an export with "Show export progress bar" enabled
1b. Run an export that fails for any reason, triggering `progress.hide()` in `catch (err)` in `exporto0o.ts`.
2. Try any Obsidian hotkey, like `ctrl + p` or `ctrl + ,`.
3. The hotkeys don't work.

Here's the error that occurs in scenario 1b:
```
plugin:obsidian-enhancing-export:28 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hide')
    at Rn (plugin:obsidian-enhancing-export:28:2932)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HTMLButtonElement.ge [as $$click] (plugin:obsidian-enhancing-export:28:9390)
```

All hotkeys stop working until restart of Obsidian, after this error occurs, or the error in #173.

**Comment by mokeyish** [comment]
duplicated with #173
