### ISSUE TITLE
Pandoc 'not found' while installed in two places. Extension doesn't seem to save settings.

### ISSUE THREAD

**Issue by j-peeters** [mokeyish/obsidian-enhancing-export#177]
Hi, I've used your plugin in the past with great results but with the latest version of Obsidian 1.6.1 it states that pandoc can't be found. While I installed it with the latest official installer in /usr/local/bin and with Homebrew in /opt/homebrew/bin.
I've tried to set the path manually but it doesn't pertain. I checked permissions on the Obsidian folder and your plugin folder in it and it should be writeable.
Do you have an idea what might cause the plugin from not recognising Pandoc?

![20240523 Obsidian v1 6 1 Enhancing Export](https://github.com/mokeyish/obsidian-enhancing-export/assets/4502360/cb713962-1b8d-4dbd-a913-e24fcf87d181)

**Comment by mokeyish** [comment]
Please set the absolute path of pandoc.

**Comment by j-peeters** [comment]
Hi @mokeyish, I've tried to set the absolute path as follows:
`which pandoc` in terminal. 
This give me 
`/opt/homebrew/bin/pandoc` (I would think this is the absolute path but maybe I'm wrong?)
I filled that into your plugin settings first field.
Closed the settings window. 

When I export a file to e.g. docx format nothing happens and I noticed that the Obsidian settings window becomes inaccessible.

Any ideas how to troubleshoot this?

**Comment by mokeyish** [comment]
@j-peeters #173

**Comment by bradleydavey** [comment]
I'm having the same issue OP describes. Oddly, one device I use with pandoc version 3.1.8 has no issues. The second, with 3.2.0 is not detected by the plugin. No error issues at all either since the Obsidian update, but hotkeys go unfunctional after attempting to export.

**Comment by mokeyish** [comment]
#184
