### ISSUE TITLE
"Uncaught TypeError: Cannot read properties of undefined (reading 'setMessage')" on new vault and fresh install

### ISSUE THREAD

**Issue by UndertheScopes** [mokeyish/obsidian-enhancing-export#178]
I was having issues on my main vault with getting the exporter for function, and I tried troubleshooting by making a new fault with a fresh install of Enhanced Export plugin.

**As a test, i tried to export a .md file named test with the text "test file".**

<img width="558" alt="image" src="https://github.com/mokeyish/obsidian-enhancing-export/assets/152017693/5e7a3c72-2f02-42bd-99b0-07a48d567a19">

**This is the error that posts:**
<img width="537" alt="image" src="https://github.com/mokeyish/obsidian-enhancing-export/assets/152017693/e83f9c42-e01c-4c8d-8887-5cdfe3326335">

**Here are my plugin settings:**
<img width="537" alt="image" src="https://github.com/mokeyish/obsidian-enhancing-export/assets/152017693/991afe6c-788d-48c4-8b00-f4e1d37e79b7">
<img width="615" alt="image" src="https://github.com/mokeyish/obsidian-enhancing-export/assets/152017693/4c03b7e3-bf74-41dd-93dd-2b9679ef097f">

**And my pandoc path from terminal:**
<img width="346" alt="image" src="https://github.com/mokeyish/obsidian-enhancing-export/assets/152017693/e3f7ba39-43fd-4dba-a5b5-b363700a425b">

**Comment by mokeyish** [comment]
duplicate #173
