### ISSUE TITLE
Can no longer detect pandoc

### ISSUE THREAD

**Issue by Owlf-Dev** [mokeyish/obsidian-enhancing-export#182]
After upgrading Pandoc, the software is no longer able to detect the Pandoc installation. I tried pointing it to the directory /usr/local/bin/pandoc, but it still fails to detect Pandoc. As a result, the plugin has stopped working.

**Comment by VoyagingCoder** [comment]
the same issue on Win11

**Comment by mokeyish** [comment]
This plugin is not compatible with obsidian 1.6. There is a temporary solution in #173. If it can be solved, please close this issue and I will find time to fix it.

**Comment by Owlf-Dev** [comment]
@mokeyish took a few times but finally took. thanks for the tip!

**Comment by Owlf-Dev** [comment]
There is a temporary solution in https://github.com/mokeyish/obsidian-enhancing-export/issues/173.
