### ISSUE TITLE
Error with exporting as PDF

### ISSUE THREAD

**Issue by YmmitZtrol** [mokeyish/obsidian-enhancing-export#19]
When exporting a file as pdf using pandoc version 2.19.2 on Windows 11 I get the following error. 
![image](https://user-images.githubusercontent.com/78155592/189034839-9ff398fa-ff46-4b2f-82ff-6c118c70756f.png)

**Comment by mokeyish** [comment]
You need to install pdf-engine.

![图片](https://user-images.githubusercontent.com/16131917/189467253-8e4f1529-1eaf-44c0-b637-829629b58e85.png)


Pelase follow the guide of https://pandoc.org/getting-started.html

**Comment by chenxin0397** [comment]
![image](https://user-images.githubusercontent.com/73974352/191912686-05b5539c-c6ea-43c0-b0d4-74ed530f7c76.png)
我是不是也是一样的情况？

**Comment by mokeyish** [comment]
PDF 可以参考 https://github.com/mokeyish/obsidian-enhancing-export/issues/21#issuecomment-1250181013

不过你这导出不是 pdf 的命令。

**Comment by chenxin0397** [comment]
有中文版说明吗？

**Comment by chenxin0397** [comment]
![image](https://user-images.githubusercontent.com/73974352/192153633-e5a5bb0c-ecf7-4b24-be13-dc8f4d51ab31.png)
![image](https://user-images.githubusercontent.com/73974352/192153653-998b4239-0ed5-4638-a64d-5020b8850a6b.png)
我还是不知道我哪里设置错了

**Comment by chenxin0397** [comment]
我是windows用户，装了MiKTeX，然后就不知道怎么操作了

**Comment by mokeyish** [comment]
> 我是windows用户，装了MiKTeX，然后就不知道怎么操作了

配置下环境变量，或者设置pdf engine 的绝对路径。我也没用过 pdf 的导出，我觉得安装太麻烦了。我直接用  obsidian 官方的功能。

**Comment by mokeyish** [comment]
pandoc 简单，就一个单文件。 pdf engine ，我看了下，要安装一堆文件，还依赖其他的，就懒得搞了

**Comment by chenxin0397** [comment]
行吧，其实我就是想导出PDF的时候带大纲，目前对自带的这个功能还很满意，美中不足的就是没有大纲

**Comment by mokeyish** [comment]
> 行吧，其实我就是想导出PDF的时候带大纲，目前对自带的这个功能还很满意，美中不足的就是没有大纲

@chenxin0397  你可以摸索一下，直接用命令行，能不能搞定你这个需求，搞定了再把命令搬到这个插件来，后续就 UI 上点点，省去每次敲命令

**Comment by chenxin0397** [comment]
> > 行吧，其实我就是想导出PDF的时候带大纲，目前对自带的这个功能还很满意，美中不足的就是没有大纲
> 
> @chenxin0397 你可以摸索一下，直接用命令行，能不能搞定你这个需求，搞定了再把命令搬到这个插件来，后续就 UI 上点点，省去每次敲命令

我是图像思维，命令行对我来说太难了，一直学不会

**Comment by joezhouchenye** [comment]
同样的pandoc命令，obsidian里就是错误{1}，命令行正常

![image](https://user-images.githubusercontent.com/59191277/206622000-d846031b-ae5d-4e6c-8a87-db5402ad88f0.png)

![image](https://user-images.githubusercontent.com/59191277/206622063-375620ad-a0c7-4265-a43a-80ef77449daa.png)

**Comment by mokeyish** [comment]
> 同样的pandoc命令，obsidian里就是错误{1}，命令行正常

@joezhouchenye 指定 pandoc 的绝对路径试试，我也不能重现，只能靠你们能重现的，找解决办法了。

**Comment by joezhouchenye** [comment]
似乎跟pdf-engine的调用有关，用的miktex，另一个插件pandoc plugin导出，如果缺少宏包会跳出miktex，这个插件不会。主要pandoc plugin不能用${vaultDir}这种，还不能多配置，不太适合我。

暂时可以先导出成html之类的，再打印成pdf

**Comment by mokeyish** [comment]
> 似乎跟pdf-engine的调用有关，用的miktex，另一个插件pandoc plugin导出，如果缺少宏包会跳出miktex，这个插件不会。主要pandoc plugin不能用${vaultDir}这种，还不能多配置，不太适合我。
> 
> 暂时可以先导出成html之类的，再打印成pdf

就是说导出 html 是正常的，是么？我当初加 html 导出，也是因为导出 pdf 不能很好的显示 gif 动画，分享给同事就不太好，但导出 html 的话，gif 动画就可以正常显示了。

**Comment by joezhouchenye** [comment]
html正常的，就是xelatex调用的问题，打开调试可以看到出错。

![image](https://user-images.githubusercontent.com/59191277/207233143-7d934b4f-5d93-4db3-976c-12a1f503ae1a.png)

Environment HOME is not set.

貌似Obsidian里调用的cmd无法获取系统的环境变量？

Pandoc Plugin貌似调用方式不一样，他的调试Console里没有cmd: 加pandoc命令这样的显示，是直接插件给的信息

**Comment by joezhouchenye** [comment]
有空再试试，虽然感觉不会再这么用了，直接自带的导出算了。

之前是想参考文献啥的，pandoc可以，还写了obsidian格式转换的filter啥的。

现在觉得太麻烦了，还不能实时看到效果，用回了vscode，把md文件放obsidian库里管理一样，没必要纠结。

**Comment by mokeyish** [comment]
Currently, the `--pdf-engine` can be [typst](https://github.com/typst/typst/releases/tag/v0.3.0), typst is easy to install. (The latest pandoc is required) 

![图片](https://user-images.githubusercontent.com/16131917/236636811-ea600342-d46e-42a6-88c8-3ce67a87a88d.png)
