### ISSUE TITLE
FR：是否可以增加用命令面板导出的功能

### ISSUE THREAD

**Issue by YIRU69** [mokeyish/obsidian-enhancing-export#2]
很高兴发现这个插件，谢谢作者！
1. 我发现只能通过点击导出为来导出，是否可以考虑增加命令指令进行导出
2. 覆盖提醒的能否保留之前的选择状态，而不是要重复的点击

**Comment by YIRU69** [comment]
另外我导出pdf的时候出现了问题，我同样的导出word和html是成功的
error: Command failed: pandoc -f markdown --resource-path="D:\Mybase\200-Learning\240-Learning-English\2401-English Word" --self-contained --metadata title="🅰Word-occident" -s -o "C:\Users\Administrator\Desktop/🅰Word-occident.pdf" -t pdf  "D:\Mybase\200-Learning\240-Learning-English\2401-English Word\🅰Word-occident.md"
pdflatex not found. Please select a different --pdf-engine or install pdflatex

**Comment by mokeyish** [comment]
- 导出命令？具体是怎样？是自动打开导出界面，还是使用上一次的配置，直接导出。
- 覆盖提醒的能否保留之前的选择状态，这个保存成功会记录下来的
    https://github.com/mokeyish/obsidian-enhancing-export/blob/47bdad9f83d9cc6d05d8df0ea54a0b2b5120d817/src/ui/export_modal.ts#L213-L217

**Comment by mokeyish** [comment]
> 另外我导出 pdf 的时候出现了问题，

导出 PDF 比较麻烦，貌似还要继续装 pdf-engine，
这是 pandoc 的文档 https://pandoc.org/MANUAL.html#option--pdf-engine

你也看看，能不能找到解决办法？找到解决办法，帮忙更新一下这个命令模板
https://github.com/mokeyish/obsidian-enhancing-export/blob/master/src/export_command_templates.ts

**Comment by mokeyish** [comment]
pdf 的也许你可以参考这个

https://gowa.club/macOS/pandoc从markdown到pdf与docx全过程.html

**Comment by YIRU69** [comment]
好的，谢谢回复
暂时不折腾，先使用原有的pdf导出

**Comment by mokeyish** [comment]
@YIRU69  命令指令，快捷键导出加上了，你现在可以配置使用快捷键了。

![image](https://user-images.githubusercontent.com/16131917/168320826-fc8bbe52-3aa8-436f-a84f-b367828e5e57.png)

**Comment by YIRU69** [comment]
谢谢
