### ISSUE TITLE
[feature request] implement ${vaultDir} variable

### ISSUE THREAD

**Issue by fruchtblase** [mokeyish/obsidian-enhancing-export#20]
Hey thanks you for this awesome plugin!

I finally found a way to remove wikilinks form markdown export [pandoc-wikilinks-filter](https://github.com/riceissa/pandoc-wikilinks-filter), but the problem is that my vault has various levels subfolders, while the filter is installed in the vault root.
So setting the filter path relative to the current file is not possible and setting an absolute path makes the vault less portable.
Having a `${vaultDir} (or ${vaultRoot})` variable would make specifying filters an bibliography files across platforms much easier.
What do you think? 

Kind regards 
fruchtblase

**Comment by mokeyish** [comment]
@fruchtblase Hi, I have add `${vaultDir}` variable. you can try the latest version 1.1.5.

**Comment by fruchtblase** [comment]
Works great, thank you so much for implementing it!
