### ISSUE TITLE
Use of deprecated pandoc flag in PDF export template

### ISSUE THREAD

**Issue by jhelwig** [mokeyish/obsidian-enhancing-export#21]
Trying to export to PDF using pandoc 2.19.2, I get an error saying `Deprecated: --self-contained. use --embed-resources --standalone`.

Looking at the export command templates, it looks like the PDF template is the only one still using `--self-contained`: https://github.com/mokeyish/obsidian-enhancing-export/blob/3079f1cc05c846e7bedb4b1dbcda825bdd8f40ba/src/export_command_templates.ts#L50-L56

Creating a new export setting copied from the default PDF one, and replacing `--self-contained` with `--embed-resources --standalone` got rid of the error, and successfully exported a PDF for me.

**Comment by mokeyish** [comment]
Thanks! I have fix it, you can try the latest version.

**Comment by mokeyish** [comment]
@jhelwig Can you help me write a brief tutorial to help those who want to export pdf with this plugin?

eg: #19

**Comment by jhelwig** [comment]
I was using macOS at the time (haven't tried doing the export on Windows, yet).

The steps for me were:
* Install `pandoc` via [Homebrew](https://brew.sh/) (`brew install pandoc`)
* Install [MacTeX](https://tug.org/mactex/mactex-download.html)
* Set `Pandoc path` in the plugin settings to `/opt/homebrew/bin/pandoc`

Now that the `--self-contained` flag is no longer being used, those were the only steps I needed to take.

**Comment by jhelwig** [comment]
Yes. Thanks!
