### ISSUE TITLE
Html Pandoc extra arguments not saving

### ISSUE THREAD

**Issue by Nickiel12** [mokeyish/obsidian-enhancing-export#22]
I have a stylesheet that I was to pass to pandoc with `-c stylesheet.css` and it works when I put that in "extra arguments". But the next time I open Obsidian, it resets the "extra arguments" field, and it doesn't render with the stylesheet.

**Comment by aaylnx** [comment]
Did you ever figure this out? I'm trying to specify a css file to use with exported epub files, but I've been unable to get my style sheet to work. I've tried using the -c option that you mention along with some other options listed here - https://pandoc.org/MANUAL.html.

If there's a way to stipulate the css.epub, I'd love to figure out how to do that!

**Comment by mokeyish** [comment]
@Nickiel12 Sorry, I can't reproduce it.


![图片](https://user-images.githubusercontent.com/16131917/195966308-bc8452d4-4759-41cc-8899-8928085b8b37.png)

![图片](https://user-images.githubusercontent.com/16131917/195966330-a1a55330-b8d1-400c-bdf8-90d379e473f2.png)

**Comment by Nickiel12** [comment]
> Did you ever figure this out? I'm trying to specify a css file to use with exported epub files, but I've been unable to get my style sheet to work. I've tried using the -c option that you mention along with some other options listed here - https://pandoc.org/MANUAL.html.
> 
> If there's a way to stipulate the css.epub, I'd love to figure out how to do that!

Are CSS files supported for rendering epub files?

**Comment by Nickiel12** [comment]
@mokeyish Well, I tried again and it cleared like in the original post. Then obsidian updated to v1.0.0, and now it appears to be working. 
Thank you!
