### ISSUE TITLE
Pandoc command not found

### ISSUE THREAD

**Issue by tim-hilde** [mokeyish/obsidian-enhancing-export#23]
I get the error that the pandoc command is not found even though I set `/opt/homebrew/bin/pandoc` as the path in the settings.

**Comment by mokeyish** [comment]
This is strange. Please run `/opt/homebrew/bin/pandoc -v`, and show me the output.

https://github.com/mokeyish/obsidian-enhancing-export/blob/39bf85c2ad3df36c2b37fd87e53f48333c38ca3f/src/exporto0o.ts#L148-L153

**Comment by tim-hilde** [comment]
@mokeyish `/opt/homebrew/bin/pandoc -v` ouputs the following:

```
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: /Users/tim/.pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

Running just `pandoc -v` has the same result btw

**Comment by mokeyish** [comment]
@tim-hilde Please try `ln -s /opt/homebrew/bin/pandoc /usr/local/bin `

**Comment by mokeyish** [comment]
The latest version already supports to detect the pandoc version.

![图片](https://user-images.githubusercontent.com/16131917/225947322-23b281a1-f523-4b99-ba9a-62bac3b5afa5.png)
