### ISSUE TITLE
can't export attachments when export WORD

### ISSUE THREAD

**Issue by Eunsolfs** [mokeyish/obsidian-enhancing-export#24]
The word file can be exported normally, but the image attachments in the md file cannot be exported to the generated word file correctly.
Whether this is related to my attachment folder settings and inline types in OB

---

能够正常的导出word文件，但md文件中的图片附件却没能正确的导出到生成的word文档中。
这是否与我在ob中的附件文件夹设置及内联类型有关

---

![image](https://user-images.githubusercontent.com/53815751/194687168-faae108c-0c0d-493b-8f96-55a9223cf298.png)

**Comment by mokeyish** [comment]
得用标准的 markdown 语法，不然 pandoc 解析不了，例如 Obsidian 独有的 wiki link 就不支持。

**Comment by Eunsolfs** [comment]
是否可以通过修改插件的js代码来实现自动识别并转换?
用户自己选择是否启用此功能



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月08日 12:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [mokeyish/obsidian-enhancing-export] can't export attachments when export WORD (Issue #24) |

得用标准的 markdown 语法，不然 pandoc 解析不了，例如 Obsidian 独有的 wiki link 就不支持。

**Comment by mokeyish** [comment]
可以修改，不过不是 js , 是 lua（不然就用正则表达式，再转换之前提前替换成标准 markdown）。 建议还是用标准 markdown 比较好，这样 typroa 及其他 markdown 编辑也能打开使用。

**修改的话**
最好是修改 reader, 因为 reader 是解析器，但比较麻烦。
https://pandoc.org/custom-readers.html

这个仓库里用的是 lua-filter https://pandoc.org/lua-filters.html
https://github.com/mokeyish/obsidian-enhancing-export/blob/master/lua/markdown.lua


例如这一段，修复数学公式块的解析，原来是解析错了，修正完再 return 正确的 el。有兴趣的话，你可以看看。

https://github.com/mokeyish/obsidian-enhancing-export/blob/39bf85c2ad3df36c2b37fd87e53f48333c38ca3f/lua/markdown.lua#L156-L177

**Comment by Eunsolfs** [comment]
好的谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月08日 12:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [mokeyish/obsidian-enhancing-export] can't export attachments when export WORD (Issue #24) |

可以修改，不过不是 js , 是 lua（不然就用正则表达式，再转换之前提前替换成标准 markdown）。 建议还是用标准 markdown 比较好，这样 typroa 及其他 markdown 编辑也能打开使用。

修改的话
最好是修改 reader, 因为 reader 是解析器，但比较麻烦。
https://pandoc.org/custom-readers.html

这个仓库里用的是 lua-filter https://pandoc.org/lua-filters.html
https://github.com/mokeyish/obsidian-enhancing-export/blob/master/lua/markdown.lua

例如这一段，修复数学公式块的解析，原来是解析错了，修正完再 return 正确的 el。有兴趣的话，你可以看看。

https://github.com/mokeyish/obsidian-enhancing-export/blob/39bf85c2ad3df36c2b37fd87e53f48333c38ca3f/lua/markdown.lua#L156-L177

**Comment by Herat1974** [comment]
I'm having this same problem. My exports don't include the image, but rather: [[image_filename.jpg]], instead of the actual image. 

<img width="817" alt="Screen Shot 2023-01-22 at 2 39 35 PM" src="https://user-images.githubusercontent.com/102617994/213939220-fd4140f1-b836-40ca-9dd7-ecfa536edc66.png">

Could someone tell me (in english please) if this is a known issue or if you guys were able to figure it out?

**Comment by mokeyish** [comment]
> Could someone tell me (in english please) if this is a known issue or if you guys were able to figure it out?

It is a known issue，The solution to solve it is correcting it to standard markdown syntax by pandoc lua-filter.

**Comment by Eunsolfs** [comment]
another solution is using standard MD attachment style, in a word,using the ()[].There is an obsidian setting, which controls the style,you can find and test it.

In a word,you need to convert the obsidian attachment style with standard MD attachment style.



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/30/2023 11:51 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [mokeyish/obsidian-enhancing-export] can't export attachments when export WORD (Issue #24) |

Could someone tell me (in english please) if this is a known issue or if you guys were able to figure it out?

It is a known issue，The solution to solve it is correcting it to standard markdown syntax by pandoc lua-filter.
