### ISSUE TITLE
Cannot export to PDF: $$ symbols surrounding align environment fails the process

### ISSUE THREAD

**Issue by LucunJi** [mokeyish/obsidian-enhancing-export#25]
This is similar to #8 , but with a different behavior: the exporting process just fails.

### Test document:
```markdown
$$
\begin{align*}
a&=b\\
&=c
\end{align*}
$$
```

### Result:
![Screenshot_20221011_182838](https://user-images.githubusercontent.com/36262513/195216705-9f20e24c-a357-4dfb-a116-b19cdb9d368c.png)

### My fixes:
add a lua filter:
```lua
return {
    {
        Math = function (elem)
            if elem.text:find("^%s*\\begin{") ~= nil then
                return pandoc.RawInline('tex', elem.text)
            else
                return elem
            end
        end,
    }
}
```

**Comment by mokeyish** [comment]
Thanks for your feedback! Could you please provide a PR that suits your situation as I have never used this plugin to export DPF and I don't have any pdf engine installed on my machine.

**Comment by LucunJi** [comment]
> @LucunJi Thanks for your feedback! Could you please provide a PR that suits your situation as I have never used this plugin to export DPF and I don't have any pdf engine installed on my machine.

Sorry I may not have time to look into the code over recent months. I think this answer https://tex.stackexchange.com/a/412984 also well explains this issue.

**Comment by mokeyish** [comment]
@LucunJi Hi, 
Please update this plugin to latest version, I have add your to fixes to the source code, but I not tested it, you can try. Please tell me, if it solved your problem.

**Comment by LucunJi** [comment]
> @LucunJi Hi, Please update this plugin to latest version, I have add your to fixes to the source code, but I not tested it, you can try. Please tell me, if it solved your problem.

Thank you! Just tried the new version and strangely the `pdf.lua` file does not have the filename suffix and becomes `pdf`, so cannot be correctly executed. Tried both updating and installing after uninstalling.

Besides this issue, the latest version works well.

**Comment by mokeyish** [comment]
Thanks, I've found that I forgot to add '.lua' subffix to pdf. I'll fix it late today.

https://github.com/mokeyish/obsidian-enhancing-export/blob/9feec47f7c5ee9dfff5f2919afefeeaad8c3332f/src/lua.ts#L9-L17

**Comment by mokeyish** [comment]
@LucunJi Hello, I've fix it.

**Comment by LucunJi** [comment]
> @LucunJi Hello, I've fix it.

Thank you

**Comment by LucunJi** [comment]
I am very sorry that I made mistakes and please remove this filter. `align*` and `align` are not supposed to be used in math environments. The correct replacement is `aligned`. The same applies to the export option in Jupyter Notebook and elsewhere, and I guess it is an intended design of pandoc.

Another issue is that my script can break environments such as `matrix` and `cases`.

**Comment by mokeyish** [comment]
Please report this issue to offial repo of pandoc?
