### ISSUE TITLE
Cannot find the export button

### ISSUE THREAD

**Issue by wangliang1989** [mokeyish/obsidian-enhancing-export#27]
On Mac, I have installed the plugin and enable it:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/12059719/196334207-0608985a-b043-4ca2-a7d6-c3fdc1031246.png">

And installed pandoc:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/12059719/196334359-c8ba4d0d-ffd8-46b1-b668-3248648faf77.png">

But cannot find the new export button in the file menu:
<img width="399" alt="iShot_2022-10-18_12 12 28" src="https://user-images.githubusercontent.com/12059719/196334441-800e3d89-6575-4337-b14a-fe0eff8e275d.png">

**Comment by mokeyish** [comment]
选择文件右键，或者打开后，右上角菜单。

**Comment by wangliang1989** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/12059719/196348457-5811a46b-13a6-4160-a1cc-de000e86e18c.png">

**Comment by mokeyish** [comment]
看看是不是这个问题：https://github.com/mokeyish/obsidian-enhancing-export/issues/9

你指定 padoc 的绝对路径，然后拿生成的命令放终端上直接跑一下看看。
