### ISSUE TITLE
Settings not stored 

### ISSUE THREAD

**Issue by dantveita** [mokeyish/obsidian-enhancing-export#28]
After making changes to the plugin settings, like switching off "Open exported file", and restarting, the setting is turned back on. Also experienced that custom arguments have been reset upon relaunch.

**Comment by PxaMMaxP** [comment]
Hello,

I have found a workaround.

In the file data.json in "\.obsidian\plugins\obsidian-enhancing-export" the settings are stored.

An example for "Open exported file" is attached.

You must add this line:
  "openExportedFile": false,

[data.txt](https://github.com/mokeyish/obsidian-enhancing-export/files/10934527/data.txt)

If you search other settings, look at https://github.com/mokeyish/obsidian-enhancing-export/blob/master/src/settings.ts

**Comment by mokeyish** [comment]
This issue should have been fixed by the latest version.
