### ISSUE TITLE
Error exporting to PDF

### ISSUE THREAD

**Issue by aknisly** [mokeyish/obsidian-enhancing-export#29]
To get past other errors, I've added --pdf-engine-xelatex to my custom command, and now I can get this to work from the command line:
`pandoc Untitled\ 1.md -f markdown --standalone --lua-filter="/home/akn/Obsidian/.obsidian/plugins/obsidian-enhancing-export/lua/pdf.lua" --embed-resources --pdf-engine=xelatex -s -o test1.pdf`

This is my custom command:
`-f markdown --resource-path="${currentDir}" --resource-path="${attachmentFolderPath}" --lua-filter="${luaDir}/pdf.lua" --embed-resources --standalone --metadata title="${currentFileName}" --pdf-engine=xelatex -s -o "${outputPath}" -t pdf`

The error message that pops up in Obsidian is simply:
`/bin/sh/sh: 0: Illegal option -`

I can export using the built-in commands for most of the others: epub, rtf, mediawiki, latex, docx, odt, html

Any ideas?

**Comment by mokeyish** [comment]
Hi [aknisly](https://github.com/aknisly):
    Have you try execute the command generated by this plugin directly? This plugin just generates command from templete for pandoc, then execute it.

**Comment by aknisly** [comment]
Ahha--it works! I'm not sure what changed, but I updated pandoc, and installed several packages trying to get this to work, and never went back and tried the built-in export. 

It would be great to tweak the output now (margins, font, etc); can that be done with the built-in pdf export?

Thanks very much for your speedy reply!

**Comment by mokeyish** [comment]
Sorry I may not have time to add extra features over recent month.

**Comment by mokeyish** [comment]
BTW, you can try to implement it yourself.
