### ISSUE TITLE
Should this work?

### ISSUE THREAD

**Issue by fncll** [mokeyish/obsidian-enhancing-export#3]
I am receiving the error "You caught an error! etc. " When I insert a new quote block, the authors don't show up. I have cleared metdata cache and re-scanned. 

I have the following in one file:

```
:::One Person:::

> Quote A is a very very short quote.

> Quote B is another quote, not too long, not too short...but something in between.

:::Another Person:::

> Quote C is longer. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui official

#quote
```

and in another, this:

```
```localquote
id V6h57
author One Person
refresh 1s
```

**Comment by mokeyish** [comment]
Hi [fncll](https://github.com/fncll):

Both `html` and `markdown` are exported success. Do you have `pandoc` installed?

![image](https://user-images.githubusercontent.com/16131917/167269677-e7ccf63d-c849-458e-91c2-aaeb3c30a739.png)

**Comment by fncll** [comment]
Sorry, I posted this question to the wrong place!
