### ISSUE TITLE
Export not working on Mac

### ISSUE THREAD

**Issue by ih8snow** [mokeyish/obsidian-enhancing-export#30]
Hi,
I followed all instrurctions and export works with the "pandoc plugin".
Using your plugin I get error messages for all formats like the one below.
Any help?
Running latest Mac OS  and current Obsidian version

Command: /usr/local/bin/pandoc -f markdown --resource-                     x
path="/Users/4me/Documents/Second Brain/001-Projects/700-02 PV-
Anlage" --resource-path="/Users/4me/Documents/Second Brain/001-
Projects/700-02 PV-Anlage/attachments" --lua-
filter="/Users/4me/Documents/Second Brain/.obsidian/plugins/obsidian-
enhancing-export/lua/pdf.lua" --embed-resources --standalone --metadata
title="Sonnen Solar Anlage" -s -o "/Users/4me/Documents/Dokumente -
MacBook Air von Jérn/Sonnen Solar Anlage.pdf" -t pdf
"/Users/4me/Documents/Second Brain/001-Projects/700-02 PV-
Anlage/Sonnen Solar Anlage.md", Error: Command failed:
/usr/local/bin/pandoc -f markdown --resource-
path="/Users/4me/Documents/Second Brain/001-Projects/700-02 PV-
Anlage" --resource-path="/Users/4me/Documents/Second Brain/001-
Projects/700-02 PV-Anlage/attachments" --lua-
filter="/Users/4me/Documents/Second Brain/.obsidian/plugins/obsidian-
enhancing-export/lua/pdf.lua" --embed-resources --standalone --metadata
title="Sonnen Solar Anlage" -s -o "/Users/4me/Documents/Dokumente -
MacBook Air von Jérn/Sonnen Solar Anlage.pdf" -t pdf
"/Users/4me/Documents/Second Brain/001-Projects/700-02 PV-
Anlage/Sonnen Solar Anlage.md" Error running filter
/Users/4me/Documents/Second Brain/.obsidian/plugins/obsidian-enhancing-
export/lua/pdf.lua: cannot open /Users/4me/Documents/Second
Brain/.obsidian/plugins/obsidian-enhancing-export/lua/pdf.lua: No such file
or directory

**Comment by mokeyish** [comment]
Thanks for your feedback! does the file `/Users/4me/Documents/Second
Brain/.obsidian/plugins/obsidian-enhancing-export/lua/pdf.lua` exists?

**Comment by mokeyish** [comment]
Usually, the lua scripts are automatically saved to the hard disk when installing for the first time or upgrading .

https://github.com/mokeyish/obsidian-enhancing-export/blob/43d28e96322fde1d5ecdcdd00291cfeaf4b33dca/src/main.ts#L97-L100

**Comment by ih8snow** [comment]
Hi,

thanks for the quick reply, there is no such file pdf.lua or folder (lua)

**Comment by mokeyish** [comment]
Maybe it's because icloud doesn't automatically sync `*.lua`. Please try another folder and reinstall the plugin.

**Comment by mokeyish** [comment]
Or download the files [here ](https://github.com/mokeyish/obsidian-enhancing-export/tree/master/lua) into `/Users/4me/Documents/Second
Brain/.obsidian/plugins/obsidian-enhancing-export/lua` manually.

**Comment by ih8snow** [comment]
Super,
works now. Seems that icloud sync was the problem. Used that earlier, but it's off now.

Thanks for the quick help!
