### ISSUE TITLE
可以导出的时候把图片格式从obsidian链接变成传统的markdown图片吗

### ISSUE THREAD

**Issue by cornradio** [mokeyish/obsidian-enhancing-export#33]

**Comment by mokeyish** [comment]
我近几个月都没有时间搞这个了，建议用标准的 markdnown 语法，这样除 Obsidian 之外，也可以用其他如 Typora 打开编辑。
如果你实在需要这个功能，你可以尝试自己处理一下，就是修改这个文件 https://github.com/mokeyish/obsidian-enhancing-export/blob/master/lua/markdown.lua ，思路就是用正则替换了。

**Comment by mokeyish** [comment]
#74
