### ISSUE TITLE
PDF export error

### ISSUE THREAD

**Issue by JESii** [mokeyish/obsidian-enhancing-export#34]
Got the following when exporting a small file with one picture. 
![image](https://user-images.githubusercontent.com/486/210250901-8d62e345-60cd-4e32-b102-28d989c6e89f.png)
I do have pandoc 2.19.2 installed and in the path. 
Obsidian says it's installed and I see no errors there
Any suggestions for what I'm doing wrong?

**Comment by mokeyish** [comment]
Sorry for late reply, this plugin is base on `pandoc`, please copy the generated export command to Termnal and execute directly.

**Comment by roginissaf** [comment]
I get the same error when exporting to PDF. Can you elaborate on your reply, I don't understand.  Does the plugin not export to PDF? 
I have set the path to Pandoc manually in the plugin: /opt/homebrew/bin/pandoc/ .

**Comment by EroyalBoy** [comment]
i suffer the same puzzle, and get to the same alarming. i also installed pandoc.
 so what should do ? do you have the video to show how to convert?

**Comment by Reventlow** [comment]
also have same error on fedora 38. Have pandock installed

**Comment by mokeyish** [comment]
It requires pdf engine.

https://pandoc.org/MANUAL.html#creating-a-pdf

**Comment by mokeyish** [comment]
Currently, the `--pdf-engine` can be [typst](https://github.com/typst/typst/releases/tag/v0.3.0), typst is easy to install. (The latest pandoc is required) 

![图片](https://user-images.githubusercontent.com/16131917/236636811-ea600342-d46e-42a6-88c8-3ce67a87a88d.png)
