### ISSUE TITLE
Word export fails to honor MD headings

### ISSUE THREAD

**Issue by JESii** [mokeyish/obsidian-enhancing-export#35]
When I export an Obsidian doc to word, the '#' headings are just tagged on to the end of the preceding line instead of becoming headers of some kind.

**Sample input doc:**
<img width="682" alt="CleanShot 2023-01-02 at 07 25 46@2x" src="https://user-images.githubusercontent.com/486/210251293-72e9ddf2-99ed-4de5-aabf-082eaa7a33cd.png">

**Sample output doc:**
![CleanShot 2023-01-02 at 07 26 19@2x](https://user-images.githubusercontent.com/486/210251404-37cbd953-5c39-4f9a-a6c2-daba80f8599c.png)

**Comment by mokeyish** [comment]
please try add new line before `Quick network ...`?

**Comment by JESii** [comment]
Sorry... I completely missed that email. Yes, that does solve the problem. Thanks!
