### ISSUE TITLE
导出word文档时，内嵌图片显示链接而非图片

### ISSUE THREAD

**Issue by hszcg** [mokeyish/obsidian-enhancing-export#38]
类似下面的内嵌图片，在obsidian编辑器中可以正常预览图片，而使用本插件导出word文档时，内嵌图片显示链接而非图片。

```
![[Pasted image 20230109205956.png]]
```

麻烦看看是否可以修复，谢谢

**Comment by mokeyish** [comment]
不支持 wiki link 的，建议使用标准的 markdown 图片语法。

**Comment by hszcg** [comment]
**为何要使用wiki link**

似乎obsidian编辑器默认 `ctrl + v` 插入图片的行为，就是 wiki link
如果采用markdown图片语法，我理解都需要手动修改一遍markdown文件，这样会有额外的工作量

**问题**

1、如果需要支持导出wiki link的图片，是否有可行的方案，是否有什么特殊原因（技术困难，或者破坏了某种产品设计原则）？
2、是否有办法修改obsidian编辑器  `ctrl + v` 插入图片的行为，使其自动采用 markdown 图片语法？

**Comment by mokeyish** [comment]
@hszcg 
技术上可行的，可参考 #39 , 但那位老哥，没有帮忙把这个问题一起解决了 😅，我也没时间处理这个问题。

obsidian 可以关闭 wikilinks 的。

<img width="1053" alt="图片" src="https://user-images.githubusercontent.com/16131917/212635401-5ace0e5c-1b59-4b2f-b82d-13e038cd311a.png">

我推荐关闭，关闭了之后就可以与 Typora 兼容了，毕竟 Typora 笔记书写体验更好。我也是关闭的，不用 wikilinks。
