### ISSUE TITLE
导出为word，不再段落间的换行符没有了

### ISSUE THREAD

**Issue by pisceswb** [mokeyish/obsidian-enhancing-export#4]
一个非常棒的插件，感谢作者！
但转换为word时还有点小问题，
1. 导出为word时，如果obsidian md文件中有2个换行符，则导出到docx中能够实现换行（md中的2个换行符变为了一个回车）。
2. 如果obsidian段落间只有1个换行符，则不能够换行，原换行符在docx中被替换为了一个小圆点。
希望作者能够修正，谢谢！

**Comment by mokeyish** [comment]
应该是要参考这个 https://github.com/mokeyish/obsidian-enhancing-export/blob/47bdad9f83d9cc6d05d8df0ea54a0b2b5120d817/lua/markdown.lua#L106

写个word 的 lua-filter 。
 Lua filter 的文档地址是 https://pandoc.org/lua-filters.html。

@pisceswb 把测试的 markdown 用例放上来。

我后面有时间看看怎么处理，你也可以改的。我写的那些 lua 脚本就是在做类似的事情。

**Comment by mokeyish** [comment]
目前是没有问题的，先关掉了，有问题再重新打开。
