### ISSUE TITLE
Links left broken

### ISSUE THREAD

**Issue by totry16** [mokeyish/obsidian-enhancing-export#41]
Hi. MD-links to "filename.pdf" or "filename.png" are converted to href = "filename.pdf.html" og "filename.png.html" (class="internal link"). Correcting them manually solves the error. A bug, or my settings gone wrong? Regards.

**Comment by mokeyish** [comment]
What did you meaning? I'm not undersatand. what's your input content and what's the type you want to export?

**Comment by totry16** [comment]
Obsidian vault containing md-files with links like [[Report.pdf]] exported to html rendering
 <a data-href="Report.pdf" href="Report.pdf.html" class="internal-link" target="_self" rel="noopener">Rep.pdf</a>

YiiSh skreiv måndag 16. januar 2023 10.51.41 (+01:00):



What did you meaning? I'm not undersatand. what's your input content and what's the type you want to export?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


-- 
Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com

**Comment by mokeyish** [comment]
I can't reproduce it. What's your expected ouput? Note that the wikilinks `[[wiki]]` are not support by this plugin, stanadard markdown syntax is required.

<img width="877" alt="图片" src="https://user-images.githubusercontent.com/16131917/212787234-bd99c953-58dc-4ef0-9291-3b57e9821f0f.png">

**Comment by totry16** [comment]
The problem is solved. 

YiiSh skreiv tysdag 17. januar 2023 02.02.27 (+01:00):



I can't reproduce it. What's your expected ouput? Note that the wikilinks [[wiki]] are not support by this plugin, stanadard markdown syntax is required.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


-- 
Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com
