### ISSUE TITLE
macOS 导出 PDF、Textbundle等不成功

### ISSUE THREAD

**Issue by entps** [mokeyish/obsidian-enhancing-export#44]
经测试，在macOS中除导出 Markdown 、Markdown（Hugo）、Html、Word（docx） 成功外，导出 PDF、Textbundle等不成功，
导出 PDF和Textbundle是很常用的功能，请完善，谢谢！

**Comment by mokeyish** [comment]
textbundle 有什么问题？输出格式不对？

导出 pdf 要安装 pdf-engine，参考 pandoc 官方的文档。

我最近一段时间都没空折腾这个了，你很紧急的话，可以尝试自己研究一下搞定它，这个项目也不能完全靠我抽时间搞。

**Comment by mokeyish** [comment]
最新版已修复，显示错误{1}（语言模板错了，英文没这问题）。

pdfengine 建议用 [typst](https://github.com/typst/typst/releases/tag/v0.3.0), 单文件，把路径放进环境变量即可用。需要安装最新版 pandoc 。

![图片](https://user-images.githubusercontent.com/16131917/236636637-badaa4b2-ae31-4523-9c64-08a4b482efc7.png)
