### ISSUE TITLE
Export to Hugo Markdown is not exporting images, errors with html export.

### ISSUE THREAD

**Issue by jptechnical** [mokeyish/obsidian-enhancing-export#45]
macOS 13.2.1 (22D68)
Version 1.1.8 (just upgraded)

I have tested and I can run pandoc commands on the Google Drive local filesystem (referenced in the errors), so it isn't a permissions or privacy problem. I also copied the vault to the local filesystem and tested again, I got the same results, so it isn't an issue with the Google Drive file system. I also upgraded pandoc.

- When exporting to Markdown (Hugo), a folder is created for the images named `<original-document-name>` but no images are exported.

- When exporting to Markdown, a folder is created for the images, named `<original-document-name>-images` but no images are exported.

- When exporting to HTML, an bunch of warnings that the images could not be fetched appears.
![image](https://user-images.githubusercontent.com/12360898/222846630-c412c6f7-ede3-4f04-8a90-3c69d4afe308.png)

Current settings: 
![image](https://user-images.githubusercontent.com/12360898/222842354-5ca68b86-63c1-4249-b4fc-7ab9b0cabe3a.png)

**Comment by mokeyish** [comment]
The pandoc version 2.19+ is required. It is something error with pandoc, not this plugin.
