### ISSUE TITLE
windows端导出报错1

### ISSUE THREAD

**Issue by zuojinxin** [mokeyish/obsidian-enhancing-export#46]
手动指定安装目录如下：
C:\Program Files\Pandoc\pandoc.exe
我尝试手动指定或是自动检查路径，都会报错，报错如下图
![image](https://user-images.githubusercontent.com/118601868/222951790-c4dcb629-d0f9-477e-9adf-bb4a0b431674.png)

**Comment by mokeyish** [comment]
这个我没办法帮你解决的，这个插件只是生成导出命令而已，路径报错，得你自己找解决办法，建议去看 pandoc 的文档，试试手工输入命令。word 导出，我这边 windows macos linux 都没问题。

**Comment by zuojinxin** [comment]
我尝试重新安装pandoc 3.1，现在能够导出markdown和word格式，但是word格式没有排版，PDF导出依旧报错{1}
![image](https://user-images.githubusercontent.com/118601868/222956618-96003666-13a8-4dff-bb39-f2fb4a2406fc.png)

**Comment by mokeyish** [comment]
这边是 2.19 版本测试的，新版本我还没用过。你看看官方文档，命令参数是不是要调整?  或者你多加个换行试试
