### ISSUE TITLE
更新之后整个obsidian卡死

### ISSUE THREAD

**Issue by lethefrost** [mokeyish/obsidian-enhancing-export#48]
因卡死时无法打开 devtools ，看不到 console 输出，逐个排查之后发现是更新 enhancing export 导致的，在 `.obsidian/community-plugins.json` 里手动删除行 `"obsidian-enhancing-export"` 来关闭本插件后得以继续运行obsidian。

系统版本：macOS Ventura 13.2.1 （apple silicon）
obsidian版本：v1.1.16

**Comment by mokeyish** [comment]
我恰好实在 windows 上测试的，现在没有苹果电脑，只能下周再看看了。

**Comment by mokeyish** [comment]
你可以先手动下载旧版本覆盖的，先不要更新了。是有人说最新版 pandoc 3.1.1 有问题，我才看看更新版本的

**Comment by lethefrost** [comment]
> 你可以先手动下载旧版本覆盖的，先不要更新了。是有人说最新版 pandoc 3.1.1 有问题，我才看看更新版本的

辛苦了，谢谢🙏

**Comment by mokeyish** [comment]
已修复，请验证一下

**Comment by lethefrost** [comment]
> 已修复，请验证一下

谢谢！问题确实解决了
