### ISSUE TITLE
Obsidian app is unresponsive after 1.1.10 update

### ISSUE THREAD

**Issue by victorstan** [mokeyish/obsidian-enhancing-export#49]
After updating to 1.1.10 version my obsidian app is unresponsive, the UI is complitely frozen and task manager shows 23% load 
![image](https://user-images.githubusercontent.com/47295057/226164970-6e057da7-2449-439b-8ca0-eaf2615f18da.png)
I unblocked myself by removing the plugin from `community-plugins.json`. Let me know if you need other info for debugging. Currently I'm on win 10 pro 22H2, i5 core 10th gen, 16 ram.

**Comment by mokeyish** [comment]
What's your pandoc version? I can't reproduce it. I'm also on windows.

**Comment by victorstan** [comment]
pandoc 3.0
Features: +server +lua
Scripting engine: Lua 5.4

**Comment by mokeyish** [comment]
reinstall this plugin?

**Comment by victorstan** [comment]
I found the issue, I disabled all the plugins and it works, so the problem is a combination between this plugin and [settings search](https://github.com/valentine195/obsidian-settings-search). Can you try this combination?

**Comment by mokeyish** [comment]
Could report it to [settings-search](https://github.com/valentine195/obsidian-settings-search)?

**Comment by mokeyish** [comment]
Please try the latest version.😆

**Comment by mokeyish** [comment]
> In general, conflicts with Settings Search happen because of issues rendering a setting tab. Settings Search just forces setting tabs to be rendered, nothing else.

I remove `Pandoc` path from System Environment variables, It happend.

Now, it seems no problem.


![图片](https://user-images.githubusercontent.com/16131917/226366357-c8787a73-7672-4884-9555-980d81e62b0e.png)

**Comment by mokeyish** [comment]
Thank you!!!
