### ISSUE TITLE
[BUG] Can't edit commmand 

### ISSUE THREAD

**Issue by Mara-Li** [mokeyish/obsidian-enhancing-export#5]
I can't click and edit the command, preventing creating custom command.

**Comment by mokeyish** [comment]
Thanks for the feedback. I've been fixed in https://github.com/mokeyish/obsidian-enhancing-export/releases/tag/1.0.5

**Comment by mokeyish** [comment]
You're welcome. Now you can search `obsidian-enhancing-export` in the community plugin of obsidian, and install it.
