### ISSUE TITLE
Default argument overrides YAML

### ISSUE THREAD

**Issue by laidbackhedgehog** [mokeyish/obsidian-enhancing-export#54]
Hi there! Could the default argument for, e.g. PDF exports, not override YAML metadata (included as a metadata block)?  Of course we could go around this by creating custom templates but it strikes me that if a title is provided in YAML then the filename (default title argument) is probably not appropriate.

**Comment by mokeyish** [comment]
Could you test it?  I remember that it will throw error if `YAML metadata` not provided.

If it is ok, PR is welcome.

**Comment by stratosgear** [comment]
I agree!  The default arguments of PDF export defines the document title to be the same as the filename, ignoring what I have setup as title in the metadata section.

I **cannot** edit the arguments section of the PDF option (it seems the textfiled is readonly) so I **cannot* remote the offending `--metadata title="${currentFileName}"` parameter.

Same with adding a new output format (for example, myPDF) and I entend the PDF setting.  I cann still NOT edit the arguments settings.

**Comment by mokeyish** [comment]
Currently, The builtin configuration are readonly.

**Comment by stratosgear** [comment]
I am sorry, but even if I follow the instructions that you provided, I **still* cannot edit the `Arguments` section of my new custom MyPDF template... :(

I can only edit/add the `Extra Arguments`. 

Same behavior as with the builtin configurations

**Comment by mokeyish** [comment]
Now the `argument` is editable.
