### ISSUE TITLE
无法导出，显示错误{1}

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [mokeyish/obsidian-enhancing-export#55]
无法导出：
<img width="1859" alt="image" src="https://user-images.githubusercontent.com/22313057/229095403-62460dec-40f8-4bcd-a7b8-e2fe1ba5f360.png">

使用指令可正常导出：
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/22313057/229095297-a06e65fc-db50-444e-a224-fd3319a73ae4.png">

已经试过重装，但是仍然无法导出。

**Comment by Lawrence-of-AnKing** [comment]
> 

更新，当我指定Pandoc的安装目录后：

<img width="827" alt="image" src="https://user-images.githubusercontent.com/22313057/229096187-7d01a709-18bf-478c-8648-54d2355c6fa8.png">

可正常转换成docx：

<img width="747" alt="image" src="https://user-images.githubusercontent.com/22313057/229096053-b5833437-6d78-4868-82e1-311656e71d85.png">


但还是无法转换成PDF：

<img width="1906" alt="image" src="https://user-images.githubusercontent.com/22313057/229095998-d1da36be-0b40-497c-be7a-82268171963d.png">

**Comment by Lawrence-of-AnKing** [comment]
> > 
> 
> 更新，当我指定Pandoc的安装目录后：
> 
> <img alt="image" width="827" src="https://user-images.githubusercontent.com/22313057/229096187-7d01a709-18bf-478c-8648-54d2355c6fa8.png">
> 
> 可正常转换成docx：
> 
> <img alt="image" width="747" src="https://user-images.githubusercontent.com/22313057/229096053-b5833437-6d78-4868-82e1-311656e71d85.png">
> 
> 但还是无法转换成PDF：
> 
> <img alt="image" width="1906" src="https://user-images.githubusercontent.com/22313057/229095998-d1da36be-0b40-497c-be7a-82268171963d.png">

破案了。

Pandoc转换成PDF时，需要用到 `pdflate` 引擎：

<img width="921" alt="image" src="https://user-images.githubusercontent.com/22313057/229105314-52af0102-4671-416d-b73a-9217b839960b.png">


我没装Tex的任何一个发行版，所以用不了。

但是新的问题还是出现了。

我安装了MikTex，并安装了 `pdflatex` 的宏包，尝试转换时，仍然蹦出错：

<img width="697" alt="image" src="https://user-images.githubusercontent.com/22313057/229105143-171fba25-4761-4622-a662-a323570510eb.png">

离谱了。

之前我在Windows上用Pandoc把md转pdf时，啥都不用装，没这许多问题啊……

**Comment by mokeyish** [comment]
pdf 支持是比较麻烦的，我自己都不用。

**Comment by NeedleCats** [comment]
感觉是中文的问题。如果latex中需要中文至少需要ctex和xelatex。但pandoc好像使用pdflatex编译的。所以会有问题。我导出英文的pdf是可以的，只有有中文就不行

**Comment by mokeyish** [comment]
最新版已修复，显示错误{1}（语言模板错了，英文没这问题）。

pdfengine 建议用 [typst](https://github.com/typst/typst/releases/tag/v0.3.0), 单文件，把路径放进环境变量即可用。需要安装最新版 pandoc 。

![图片](https://user-images.githubusercontent.com/16131917/236636637-badaa4b2-ae31-4523-9c64-08a4b482efc7.png)

**Comment by YIRU69** [comment]
@mokeyish 问一下这个问题解决了吗，我导出 PDF 的时候，还是出现了错误，原因就是中文的问题，我怀疑导出 PDF 用的是 pdflatex ，但是它不支持中文，你又使用了你说的 typst，但是它显示没有找到 typst ,我安装了，但是不知道为什么还是这样，求解决

**Comment by mokeyish** [comment]
> @mokeyish 按照你的方法成功了，但是出来的排版真的不理想，我想知道这方面可以进行修改吗

多看 pandoc 文档，应该可以的。

**Comment by Emt-lin** [comment]
@YIRU69 有没有调整好排版过，老哥。
感觉不如用 typora 导出，至少排版不会乱，如果ob和typora设置的主题和字体相近的话，那基本上导出一致了。
