### ISSUE TITLE
Feature: Ability to reference some metadata fields

### ISSUE THREAD

**Issue by stratosgear** [mokeyish/obsidian-enhancing-export#56]
Would it be possible to provide some substitution variables so that we can dynamically refer to some note metadata?

For example:

In case I have a note like:

```
---
title: My Note title
author: Me and myself
template: eisvogel
---

# Title

some simple text
```

I would like to define as `Extra arguments` on your plugin, something like: `--template ${metadataTemplate}` and have it expand to: `--template eisvogel`.  That will give us the ability to use different PDF output templates based on how each Note's metadata is defined.

That would be in addition to all the other ${outputDir}, ${outputFileFullName}, etc substitution params that you provide.

Thanks!

**Comment by mokeyish** [comment]
Good idea!! But I don't have time to work on this recently. 

If you really want this feature, I can tell you where to modify it.

1. First，we need a yaml parse to parse metadata.
   search at npmjs: https://www.npmjs.com/search?q=yaml
3. Replace the value. 

   https://github.com/mokeyish/obsidian-enhancing-export/blob/383c0f0d12d57e11763be9c8bfb7dad5b50e471b/src/exporto0o.ts#L141

**Comment by mokeyish** [comment]
The latest version has implemented it. Try `${metadata.author}`
