### ISSUE TITLE
Is there a way to invoke this on the terminal?

### ISSUE THREAD

**Issue by reagle** [mokeyish/obsidian-enhancing-export#59]
Is there a command line option?

**Comment by mokeyish** [comment]
? I don't understand what's your meaning. This plugin exports file by generating the pandoc commands. If you want to see this commands，please open the electron developer console in Obsidian.

**Comment by reagle** [comment]
My apologies, I'm migrating from Zim wiki -- and am familiar with pandoc -- and I'm looking for the equivalent of exporting a complete vault (with wik-links that work).

```
/Applications/Zim.app/Contents/MacOS/Zim --export --recursive --overwrite --output=/Users/reagle/joseph/plan/os --format=markdown  /Users/reagle/joseph/plan/zim 
```

This plugin appears to export a single file at a time all in the same export folder -- rather than their relative subfolders. However, perhaps the lua filter you developed could be modified to be used with pandoc to do a whole vault conversion?

**Comment by mokeyish** [comment]
I don't have plan to support export the whole vault. Maybe you can write a shell or python script to export the whole vault.

**Comment by reagle** [comment]
Yes, but most export scripts are janky, including my own. Thanks for the quick response.
