### ISSUE TITLE
[BUG] Custom command : Undefined extension in output

### ISSUE THREAD

**Issue by Mara-Li** [mokeyish/obsidian-enhancing-export#6]
My command line : 
```sh
pandoc -f markdown+lists_without_preceding_blankline+spaced_reference_links+hard_line_breaks+yaml_metadata_block+implicit_figures --resource-path="G:/Mon Drive/Seed/_assets/attachments/" --citeproc -L "..\pagebreak.lua" --reference-doc="..\custom-reference.docx" -s -o "${outputPath}" -t docx
```

At the moment I choose to export, Obsidian seems to crash (infinite loading without error). 

Also, I notice : 
- I need to add `pandoc` before `-f` because it doesn't be recognized : 
```sh error: Command failed: -f markdown+lists_without_preceding_blankline+spaced_reference_links+hard_line_breaks+yaml_metadata_block+implicit_figures --resource-path="G:/Mon Drive/Seed/_assets/attachments/" --citeproc -L "..\pagebreak.lua" --reference-doc="..\custom-reference.docx" -s -o "C:\Users\Lili\Downloads/Introduction.docx/Introduction.docx" -t docx
'-f' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.
```
- Custom doesn't append `.docx` (I have undefined)
- Editing `docx` export give me error because of filter lua path (`..\`) : 
```sh
error: Command failed: pandoc -f markdown --resource-path="G:\Mon Drive\Seed\10. Master\Stage\mémoire\Introduction" -s -o "C:\Users\Lili\Downloads/Introduction.docx" -t docx -f markdown+lists_without_preceding_blankline+spaced_reference_links+hard_line_breaks+yaml_metadata_block+implicit_figures --resource-path="G:/Mon Drive/Seed/_assets/attachments/" --citeproc -L "..\pagebreak.lua" --reference-doc="..\custom-reference.docx" "G:\Mon Drive\Seed\10. Master\Stage\mémoire\Introduction\Introduction.md"
Error running filter ..\pagebreak.lua:
cannot open ..\pagebreak.lua: No such file or directory
```

**Comment by Mara-Li** [comment]
Also, maybe change `text` by `textArea` for settings. It will be better !

**Comment by mokeyish** [comment]
> filter lua path (..\) :

The relative path may cause error.  You' d better put lua files into `${pluginDir}/lua` and use `${pluginDir}/lua/path/to/your/file`.

eg.
https://github.com/mokeyish/obsidian-enhancing-export/blob/eb2ef66e91f597725f96a840f9fbfc75e8ca30b1/src/export_command_templates.ts#L22-L24

**Comment by Mara-Li** [comment]
I successfully to do my conversion after a lot of work and try! I will use a default file and metadata for my title & configuration command. 
The only bug remaining is the export extension : I always have this undefined extension.

**Comment by Mara-Li** [comment]
![image](https://user-images.githubusercontent.com/30244939/168131297-09c3b326-68bc-4a28-bc54-161e3521c44e.png)

**Comment by mokeyish** [comment]
Sorry I test less about `custom export command`. I'll try to fix it this weekend.

**Comment by mokeyish** [comment]
My original intention of writing this plugin is to be easily to export to Hugo( https://gohugo.io )'s blog ( https://yish.vip ).  And share my markdown notes with html, since markdown can't show GIF. this two export command have been added to default settings of this plugin.🤣

**Comment by mokeyish** [comment]
This issue reminds me that the attachment path of obsidian config should also be append to `--resource-path`.

**Comment by Mara-Li** [comment]
Yes it can be pretty cool !

**Comment by mokeyish** [comment]
I've fixed it, you can try it now.  If you have any questions, please tell me here.
![image](https://user-images.githubusercontent.com/16131917/168180049-ef293f44-52f9-4eef-841d-015ad6d09a5c.png)

**Comment by mokeyish** [comment]
@Mara-Li Hi [Mara-Li](https://github.com/Mara-Li)
Is there any other questions? Can this issue be closed?

BTW, What is the direction of your master's degree? Machine learning? This [website](https://math.yish.org/) may help you to do math equation notes with obsidian. More equations snippets can be add to [here](https://github.com/mokeyish/Latex-Equation-Editor/blob/master/list_latexs.json).

**Comment by Mara-Li** [comment]
Oh, I will be love to work on it but I'm in epidemiology ! No need (by chance) for formula :'D.
