### ISSUE TITLE
Running obsidian in flatpak, whats the path to pandoc?

### ISSUE THREAD

**Issue by Sirtz** [mokeyish/obsidian-enhancing-export#61]
Hey, I am using fedora linux, and obsidian is running as a flatpak. I have installed pandoc. Putting /usr/bin/pandoc into the plugin settings does not work, because flatpaks cannot open system files like that. Do you have an idea on how to get around this? I would love if this would work, thank you!
Edit: If you would just let me copy the command that errors out, it would help a lot, I could just paste it into terminal and it would work! I just can't select anything on the error message.
![image](https://user-images.githubusercontent.com/26656736/235945536-7c30bb96-1c5a-475c-a507-f5b5fb0df947.png)

**Comment by mokeyish** [comment]
Disable the optiom `open exported file`? It seems an error with opening the exported file due to the `$DISPLAY` is undefined.

**Comment by IntoTheVoid-900** [comment]
I have tried that, but I am still getting the same error

**Comment by IntoTheVoid-900** [comment]
I have found a solution that works, although it isn't ideal. If you place the static Pandoc binary inside one of an Obsidian directory (I used `~/.var/app/md.obsidian.Obsidian/~/.bin`, and set the plugin to use its path, it seems to work well. You don't even need the `flatpak-spawn --host`.

**Comment by mokeyish** [comment]
It may be a permission problem, or it may be a path mounting problem.

https://docs.flatpak.org/en/latest/sandbox-permissions.html

**Comment by Sirtz** [comment]
Chatgpt solved this for me: 
1. Give Obsidian Flatpak permissions for all system files, I used flatseal for that. It's a gui for flatpak permissions.
2. Create a script somewhere, in my case `/home/fritz/Bin/pandoc-wrapper.sh`
3. Content of the script: 
``` 
#!/bin/sh
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
exec flatpak-spawn --host /usr/bin/pandoc --pdf-engine=xelatex "$@"
```
4. Make the script executable: `sudo chmod +x pandoc-wrapper.sh`
5. Make sure you have pandoc and latex installed. [Latex instructions are here](https://unix.stackexchange.com/questions/199638/how-to-fully-install-latex-in-fedora)
6. Open the Obsidian Enhancing Export settings and point the pandoc path to our pandoc-wrapper.sh, `/home/fritz/Bin/pandoc-wrapper.sh`

That should work, let me know if it doesn't. Or try to debug with chatgpt 4, that's what I used anyway.

**Comment by mokeyish** [comment]
For image, please use`![](path to image)` instead.

wiki links are not parsed by pandoc.

**Comment by Sirtz** [comment]
All my images are stored in my Vault, in a folder called "Assets". Can you give me an example on how the ![](path to image) would work?

**Comment by mokeyish** [comment]
I mean that you should not use wiki links in the obsidian. turn off the wiki links in the settings of Obsdian and convert `[[path to image]]` to `![path to inage]`.

This plugin will add `Assets` to final export command by setting 
https://github.com/mokeyish/obsidian-enhancing-export/blob/04176511ba5f07bfa1073919bee0c12a9ceb4855/src/export_command_templates.ts#L5

which read from the obsidian configuration.

**Comment by mokeyish** [comment]
If you are willing to let pandoc support wiki links, you can try to write a lua script to automatically convert.
https://pandoc.org/lua-filters.html

If the converting script is `wiki-links.lua`.
then uodate the export template command 
https://github.com/mokeyish/obsidian-enhancing-export/blob/04176511ba5f07bfa1073919bee0c12a9ceb4855/src/export_command_templates.ts#L25

to 

```diff
- -f markdown --resource-path="${currentDir}" --resource-path="${attachmentFolderPath}" --lua-filter="${luaDir}/wiki-links.lua"  --lua-filter="${luaDir}/markdown.lua" -s -o "${outputPath}" -t commonmark_x-attributes
+ -f markdown --resource-path="${currentDir}" --resource-path="${attachmentFolderPath}" --lua-filter="${luaDir}/markdown.lua" -s -o "${outputPath}" -t commonmark_x-attributes

```

**Comment by Sirtz** [comment]
Oh I am not actually using wiki links, my paths look like this: `![[Pasted image 20230419165739.png]]`
I guess this is another path issue then due to flatpak?

**Comment by mokeyish** [comment]
> Sorry didn't see your answer! I am not actually using wiki links, my paths look like this: `![[Pasted image 20230419165739.png]]` I guess this is another path issue then due to flatpak?

`![[]]` actually wiki links.

**Comment by FeralFlora** [comment]
> The biggest problem is that it is not recognising my systems `texlive`, so I cant export with PDF. Don't really know how to fix it though

According to the readme of the Flatpak Obsidian package, you need to install the following extension for pdflatex to work:

`$ flatpak install flathub org.freedesktop.Sdk.Extension.texlive//24.08`

See: https://github.com/flathub/md.obsidian.Obsidian?tab=readme-ov-file#pandoc-support
