### ISSUE TITLE
Adding tutorial for package + export to .bib template

### ISSUE THREAD

**Issue by universvm** [mokeyish/obsidian-enhancing-export#64]
Hi there, 

You mention testing Markdown, Markdown (Hugo), Html. I have tested your plugin (on MacOS) for .docx, Latex, PDF and even have a short script with lua filter to export the bib (see below). 

I use your package extensively and have covered it in my article here: https://betterhumans.pub/obsidian-tutorial-for-academic-writing-87b038060522 . If you think it's helpful feel free to link to it! 

Also I created this command to export a bib file:

```
pandoc
-f markdown
-o "${outputPath}"
--resource-path ~/Library/Mobile\ Documents/com~apple~CloudDocs/ 
--bibliography="export-data.bib" 
--to=biblatex
--lua-filter ~/Library/Mobile\ Documents/com~apple~CloudDocs/citefilter.lua 
"${currentPath}"
```

Combined with this lua filter it makes sure that only the citations used in the markdown are exported:

```
function Pandoc(d)
  d.meta.references = pandoc.utils.references(d)
  d.meta.bibliography = nil
  return d
end
```

I think it could be added to these templates: https://github.com/mokeyish/obsidian-enhancing-export/blob/master/src/export_command_templates.ts and the .lua file added here: https://github.com/mokeyish/obsidian-enhancing-export/tree/master/lua

Let me know :)

**Comment by mokeyish** [comment]
Thanks, Are you willing to submit PR?

**Comment by mokeyish** [comment]
# Here is the simple guide.

## Environment Preparing
1. Install the `nodejs`
    https://nodejs.org/en/download
2. Install the `pnpm`
    ```shell
    npm install -g pnpm
    ```
4. Clone the repositotry
    ```shell
    git clone https://github.com/mokeyish/obsidian-enhancing-export.git
    ```
5. Install dependencies

    ```shell
    cd obsidian-enhancing-export
    pnpm install
    ```
## Build

1. add `.env.local` to project root
    ```env
    # export to obsidian plugin directory directly
    OUT_DIR="path/to/.obsidian/plugins/obsidian-enhancing-export"
    ```
2. build
    The following command will build the plugin and copy it to obsidian plugin directory.
    ```shell
    pnpm run build
    ```
4. Restart this plugin or obsidian.

**Comment by universvm** [comment]
I tried adding the commands, would you mind fixing it if there's something that does not work?
