### ISSUE TITLE
Adding latex template support

### ISSUE THREAD

**Issue by universvm** [mokeyish/obsidian-enhancing-export#66]
Hi there, 

I use this plugin with templates like Eisvogel https://github.com/Wandmalfarbe/pandoc-latex-template/tree/master 

I was thinking that some of these templates could be integrated as part of the plugin. What are your thoughts? I'm not sure how the user could interact with these in terms of UI. In terms of functionality I think we can modify the pandoc code. 

Alternatively the user could specify their own templates and add them to a folder. 

Let me know what you think

**Comment by mokeyish** [comment]
The list of optional templates can be configured in the settings interface. Then, in the export interface, if it is judged that there is a template list, it will drop down to let the user select a template.

**Comment by mokeyish** [comment]
I think the current [ui code](https://github.com/mokeyish/obsidian-enhancing-export/tree/master/src/ui) is too complicated and not easy to maintain. I want to switch to [solidjs](https://www.solidjs.com/guides/getting-started), but I don't have time to do it.

**Comment by mokeyish** [comment]
I've migrated UI code to solidjs #68

**Comment by mokeyish** [comment]
Now, it is more easy to understand than before.

![图片](https://github.com/mokeyish/obsidian-enhancing-export/assets/16131917/6ab545c3-5e19-4855-bebf-a24ea62bff29)

**Comment by universvm** [comment]
Hey there, thank you for this, you're awesome! 

Small comment, I'd change "Edit Command Template" --> "Edit Pandoc Command". So that we can create a section called "Choose Latex Template". I can change it if you want :)

If you're good with it, I will spend some time creating some latex templates like:

1. Academic Template (probably based off eisvogel)
2. Academic Template 2-columns

Can you think of any others you think could be useful?

**Comment by mokeyish** [comment]
- About ` "Edit Command Template" --> "Edit Pandoc Command"`. This plugin is not only support pandoc commands, so there is a command type: 'pandoc' | 'custom'.
- Does latex support all export types? or just only `PDF`?

**Comment by universvm** [comment]
- How about `Edit Command` then? From Wikipedia: ``` The term template, when used in the context of word processing software, refers to a sample document that has already some details in place ```
- Latex template supports all the pandoc export formats: .docx, .pdf, .latex etc...

**Comment by mokeyish** [comment]
What's this meaning of ` From Wikipedia: The term template, when used in the context of word processing software, refers to a sample document that has already some details in place`?

I don't understand.


It seems not all the export formats, eg: markdown.

**Comment by mokeyish** [comment]
Eg: update the tempate

https://github.com/mokeyish/obsidian-enhancing-export/blob/2a08bf2c4ec03d597472049b5db865a7a7c4a84e/src/export_command_templates.ts#L57-L64

to 

```ts
{
    name: 'PDF',
    type: 'pandoc',
    arguments:
      '-f markdown --resource-path="${currentDir}" --resource-path="${attachmentFolderPath}" --lua-filter="${luaDir}/pdf.lua" --embed-resources --standalone --metadata title="${currentFileName}" -s -o "${outputPath}" -t pdf',
    customArguments: '--pdf-engine=typst',
    latexTemplates: [
       "latextemplateNameA": "latexTemplatePathA",
       "latextemplateNameB": "latexTemplatePathB",
   ],
    extension: '.pdf',
}
```

**Comment by mokeyish** [comment]
Then:
![图片](https://github.com/mokeyish/obsidian-enhancing-export/assets/16131917/746bf02f-260f-4ebb-80e7-9c9f21f65099)

**Comment by mokeyish** [comment]
Thank you very much if you can help implement this function. Feel free to ask me any questions about this.

**Comment by mokeyish** [comment]
I think both are ok 😊. looking forward to your PR.

**Comment by mokeyish** [comment]
I've added [CONTRIBUTING](https://github.com/mokeyish/obsidian-enhancing-export/blob/main/CONTRIBUTING.md) document.But my English is not good😂, and writing is relatively simple.

**Comment by universvm** [comment]
Thank you!

**Comment by universvm** [comment]
@mokeyish I am almost done with the code but I encounter this error after following your guide:

`failed to load config from /Users/leo/Documents/code/obsidian-enhancing-export/vite.config.ts
error during build:
Error: ENOENT: no such file or directory, lstat 'dist'`

Any chance you know what may be happening? I followed this guide: https://github.com/mokeyish/obsidian-enhancing-export/blob/main/CONTRIBUTING.md

**Comment by mokeyish** [comment]
> @mokeyish I am almost done with the code but I encounter this error after following your guide:
> 
> `failed to load config from /Users/leo/Documents/code/obsidian-enhancing-export/vite.config.ts error during build: Error: ENOENT: no such file or directory, lstat 'dist'`
> 
> Any chance you know what may be happening? I followed this guide: https://github.com/mokeyish/obsidian-enhancing-export/blob/main/CONTRIBUTING.md
> 
> Let me know if you're able to test. Also have a look at the current state of the changes: #80

Please comment these lines temporary.

https://github.com/mokeyish/obsidian-enhancing-export/blob/8345d2485a8ff0ecede4a2804d6cdf7db1a72ac5/vite.config.ts#L27-L30
