### ISSUE TITLE
不能导出markdown，提示错误{1}

### ISSUE THREAD

**Issue by irrealizable** [mokeyish/obsidian-enhancing-export#7]
我可以导出docx，odf，html等等，但是不能导出markdown

**Comment by mokeyish** [comment]
因为你的笔记库是有中文路径？我试了一下好像是这样，英文路径没问题，不过这麻烦了，没找到解决办法。

![image](https://user-images.githubusercontent.com/16131917/168171869-93aa897c-f826-4304-97b1-5e6f00292393.png)

你可以帮忙把导出命令复制出来看看要怎么解决么？

**Comment by mokeyish** [comment]
我在我的 linux 电脑也遇到 `错误{1}` 的问题了，但跟上面中文路径的好像不是同一个问题，升级到最新的 pandoc 就解决了。

**Comment by irrealizable** [comment]
升级了pandoc，有了一点改善，原来提示错误{1}，且什么文件都没有生成，现在仍然提示错误{1}，且我已经改为英文了
![image](https://user-images.githubusercontent.com/56907077/168194588-1c598e43-ab73-4f18-a536-7d4006ccf684.png)
现在是能生成markdown文件和media文件夹，但是不能拷贝附件到media路径里，且我的附件也是英文名称的
![image](https://user-images.githubusercontent.com/56907077/168194746-b39b75e3-d54c-4c07-a79b-aea6c84796c1.png)

**Comment by mokeyish** [comment]
你是什么附件？我测试图片 png 是正常的。
这里是附件提取的函数

https://github.com/mokeyish/obsidian-enhancing-export/blob/96b145e3abd5d571620ab2078c145178cc49a06d/lua/markdown.lua#L68

**Comment by irrealizable** [comment]
是jpg，报错是这样的
![image](https://user-images.githubusercontent.com/56907077/168195705-eb9ecacb-38d8-4dde-a353-706672cf99ab.png)

**Comment by mokeyish** [comment]
得把生成的执行命令单独拿到 CMD 来跑，确认一下到底是插件的问题，还是 pandoc 的问题，针对性解决。

**Comment by mokeyish** [comment]
你重置一下，我的附件是在相对子目录下的，因为要用 typora 打开来写笔记，这样能互相兼容。你是在根目录吧，

<img width="905" alt="图片" src="https://user-images.githubusercontent.com/16131917/168196150-cb7ea993-2c5b-4b62-a885-dfad8e68b0f1.png">

这个是早上新加的，读取 obsidian 配置的附件目录：
<img width="1204" alt="图片" src="https://user-images.githubusercontent.com/16131917/168196369-f064d89d-2e60-4ff8-a547-1861b8886c59.png">

**Comment by irrealizable** [comment]
我也是相对子目录的，因为我也用typora，我重装之后仍然是如此错误，无法将附件拷贝到media文件夹中
![image](https://user-images.githubusercontent.com/56907077/168196723-2fd54358-73b0-4df0-9483-b096f477cac6.png)

**Comment by mokeyish** [comment]
那得麻烦你，直接拿程序生成的命令去跑，确认一下什么问题了。我这边 windows、macos、linux 都正常的，这三个系统我都有在用的，笔记是用 syncthing 同步的。

**Comment by mokeyish** [comment]
上面那个乱码的不用介意，我是把 Nodejs cmd 调用出错，直接给打印出来了。

**Comment by irrealizable** [comment]
但是我的控制台不显示命令，它是这样的
![image](https://user-images.githubusercontent.com/56907077/168199719-190118d8-6931-4d51-a685-73764c4e8d7d.png)

**Comment by mokeyish** [comment]
手动把上面命令抄下来？官方默认的组件不支持复制😂。或者你 clone 代码，修改，去里面 debuger.
调用系统执行命令的代码在这

https://github.com/mokeyish/obsidian-enhancing-export/blob/96b145e3abd5d571620ab2078c145178cc49a06d/src/ui/export_modal.ts#L16-L22

**Comment by irrealizable** [comment]
我运行之后的报错是这样的，我不知道这个test是什么
![image](https://user-images.githubusercontent.com/56907077/168202322-22b3808d-e456-4f52-b46c-03d56b20d405.png)

**Comment by mokeyish** [comment]
把 `-media` 删了试试，就是清空导出的目标目录。`test` 我也不知道是哪的，我没写过这个。

**Comment by mokeyish** [comment]
你把你的测试 markdown 给我，我看看是不是 markdown 里面格式的问题。

**Comment by mokeyish** [comment]
@irrealizable 还有问题么?如果没问题了，就关了吧

**Comment by fallencrasher** [comment]
我的也出现了问题，windows端，可以导出word，html，不能导出PDF。导出markdown会报错误{1}，但是还是会导出来的。但是PDF真的是不能行。 @mokeyish 。我们这个PDF导出与自带的导出有什么区别吗？会更好看吗哈哈哈？

**Comment by mokeyish** [comment]
@fallencrasher 建议用自带的，pandoc 的 pdf 导出还要再装一个 engine 的，我没找到单文件绿色版的，貌似要装一堆文件，懒得折腾了。

**Comment by mokeyish** [comment]
@fallencrasher 导出 markdown 报错，你把能复现的markdown 贴上来？我看看是不是内容的问题。

**Comment by joezhouchenye** [comment]
同样的pandoc命令，obsidian里就是错误{1}，命令行正常

![image](https://user-images.githubusercontent.com/59191277/206622000-d846031b-ae5d-4e6c-8a87-db5402ad88f0.png)

![image](https://user-images.githubusercontent.com/59191277/206622063-375620ad-a0c7-4265-a43a-80ef77449daa.png)

**Comment by mokeyish** [comment]
@joezhouchenye 是很奇怪，是不是系统装了多个 pandoc ？我记得好像 conda 有一个 pandoc 但是版本比较低。看这里 #9
