### ISSUE TITLE
[bug] 显示导出成功，但没有导出图片

### ISSUE THREAD

**Issue by sun2ot** [mokeyish/obsidian-enhancing-export#71]
这是我的附件路径，在`resource/images`下
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/84566015/05991ab0-bc26-461c-8186-fb4c6686a38d)

Obsidian中配置的附件路径也是这个
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/84566015/f8c17679-822e-4495-8ef2-02146b3d3f94)

导出时确实生成了附件资源文件夹，但里面是空的
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/84566015/155842b2-dcba-4c5d-939b-13046a66e77d)

**Comment by mokeyish** [comment]
你试试把导出的命令复制出来看看？快捷键 `ctrl + shift + i` 打开控制台，可以看到生成的导出命令。

然后直接命令行跑导出命令，看看为什么图片没导出来，是路径不对？

**Comment by sun2ot** [comment]
> 生成的导出命令

```powershell
[Obsidian Enhancing Export]: export command: 
pandoc -f markdown 
--resource-path="D:\Cloud\BaiduSyncdisk\obsidian\yzh-air15\01 教程\011 搞机" 
--resource-path="resource/images" 
--lua-filter="D:\Cloud\BaiduSyncdisk\obsidian\yzh-air15/.obsidian/plugins/obsidian-enhancing-export/lua/markdown.lua" 
-s -o "C:\Users\yzh25\Desktop/阿里云对象存储 OSS.md" 
-t commonmark_x-attributes  "D:\Cloud\BaiduSyncdisk\obsidian\yzh-air15\01 教程\011 搞机\阿里云对象存储 OSS.md"
```
> 直接命令行跑导出命令
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/84566015/ee6d5f6c-c371-43f1-8257-e9750fa3980d)

上方命令行无输出，生成的资源目录依旧为空

**Comment by sun2ot** [comment]
> 你 cd 到你文档所在目录，再执行上面的命令试试。

我就是在文档所在目录执行的，忘了截图，所以后面在C盘补了一张示意图🥲。
我用的是标准的markdown图片链接：`![](resource/images/65bbd6506b94a1a54b3de85598e8329a.png)`

**Comment by sun2ot** [comment]
> 可能图片目录是二级子目录了？
破案了哈哈哈，就是这个原因✅，`![](../../resource/65bbd6506b94a1a54b3de85598e8329a.png)`，放到一级子目录就好了

**Comment by mokeyish** [comment]
不知道是 pandoc 的问题，还是这个 lua 脚本的问题，你想用二级子目录的话，可以研究看看

https://github.com/mokeyish/obsidian-enhancing-export/blob/main/lua/markdown.lua

我暂时没精力折腾这个了。

**Comment by Hot12345** [comment]
How did you solved this issue?

**Comment by sun2ot** [comment]
> How did you solved this issue?

You need to store the images in the root of the resource folder, not in the secondary

**Comment by Hot12345** [comment]
> > > How did you solved this issue?
> > 
> > 
> > You need to store the images in the root of the resource folder, not in the secondary
> 
> such as `resource/a.jpg` instead of `resource/images/a.jpg`

But if you have it in a secondary folder, how to fix this then? 
Otherwise all the pictures are around laying in the folder... That's what I don't want.

**Comment by sun2ot** [comment]
> But if you have it in a secondary folder, how to fix this then? Otherwise all the pictures are around laying in the folder... That's what I don't want.

Well...If you had set all pictures in the secondary folder, I think you can use the tool which can replace characters batches to edit the markdown picture path in the text. Then move pictures to the correct path manually.

But if you don't want to save pics in the secondary folder, I think there is no better solution than a picture bed... Or you can wait this plugin's developer to fix it.

**Comment by Hot12345** [comment]
> 

My topic / my problem. 

Exactly! I have the pictures in the workvault and in the pictures folder. 
How can I change manually the picture path what you describe? 

See my topic. Hope you can help me with it.
