### ISSUE TITLE
Cannot access to the documentations

### ISSUE THREAD

**Issue by merlinuwe** [mokeyish/obsidian-enhancing-export#72]
I cannot access to https://betterhumans.pub/obsidian-tutorial-for-academic-writing-87b038060522

Can you please copy and paste the instructions here?

I installed typst.exe in the path.

But I cannot make pdf-files. The others I hadn't tried yet.

**Comment by mokeyish** [comment]
@universvm He is the author of the article you mentioned.

@universvm Hi, could you help him?

**Comment by universvm** [comment]
Hi @merlinuwe , can you try opening the article in incognito?

**Comment by merlinuwe** [comment]
Yes it works in incognito mode. But for me, it seems to be to complicated to configure.

**Comment by universvm** [comment]
You can export a note to PDF using Obsidian - no plugin needed (CMD/CTRL + P and type "export to PDF"). 

It's difficult to understand what you mean by "I need some simple steps." if we don't know what you're stuck on other than " it seems to be to complicated to configure". It sounds like Pandoc may not be the tool you're looking for.

**Comment by merlinuwe** [comment]
Thanks for your help.

When I do this

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/4138869/6b40f827-a853-45b3-92cd-77d04b6c8562)

choose the first entry "Obsidian Enhancing Export: Export to ....

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/4138869/1d055a6b-097d-478c-a8bb-bdb375f3b459)


I get this:

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/4138869/7d33a5c2-8c68-493c-b5df-d3f50dec9a0b)

These are my settings

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/4138869/6b8cd310-47a3-4239-aec9-9af455eb682f)

C:\ProgramData\chocolatey\bin\pandoc.exe

C:\Users\uwewe\OneDrive - BBZ Dormagen\Dokumente\Desktop

-f markdown --resource-path="${currentDir}" --resource-path="${attachmentFolderPath}" --lua-filter="${luaDir}/pdf.lua" --embed-resources --standalone --metadata title="${currentFileName}" -s -o "${outputPath}" -t pdf

--pdf-engine=typst


(typst.exe is in the path)

What did I do wrong?

**Comment by universvm** [comment]
it is much easier to help you with an error message. The error is likely on typst. I've never used it before. The "simplest" solution imo would be to write in Latex.

**Comment by mokeyish** [comment]
The `typst` is single file binary, and it's easy to install. But it seems that typst still a experimental feature added recently https://github.com/jgm/pandoc/issues/8713. You need to install nightly pandoc from [here](https://github.com/jgm/pandoc/actions/runs/5043225326).

If there are no other additional requirements, it is recommended to use the official builtin `Export to PDF`（not this plugin）. save trouble

**Comment by mokeyish** [comment]
Please update the version, I found some bugs and fixed them.
