### ISSUE TITLE
导出md无图片，导出word报错

### ISSUE THREAD

**Issue by HopeLHP** [mokeyish/obsidian-enhancing-export#79]
系统macos13.3
ob设置：
<img width="833" alt="image" src="https://github.com/mokeyish/obsidian-enhancing-export/assets/70339118/27c9110f-b32b-4a58-8f03-ad6352003e9d">
<img width="836" alt="image" src="https://github.com/mokeyish/obsidian-enhancing-export/assets/70339118/64a3ba63-300b-4a5c-8261-394b92c55fbc">
错误界面：
<img width="550" alt="image" src="https://github.com/mokeyish/obsidian-enhancing-export/assets/70339118/49c7a328-cf1d-4d70-bc42-b9553e4ed3b1">
导出md未报错但没有图片，导出docx没图片同时报错。

**Comment by mokeyish** [comment]
你复制生成的命令到你的命令行终端执行看看，这个命令是生成错了，还是要怎么调整。

**Comment by HopeLHP** [comment]
具体是哪个命令，直接复制参数那段吗

**Comment by HopeLHP** [comment]
确定原因了，就是找不到图片，把图片语法改成相对路径就可以导出。
原：
![](Assets/1685688431818.png)
改：
![](../Assets/1685688431818.png)
