### ISSUE TITLE
Export to .Docx without attachment

### ISSUE THREAD

**Issue by Hot12345** [mokeyish/obsidian-enhancing-export#82]
Hi

I use this pluging, but if I export it to .Docx then its without attachment.
And the .png attachments is in a subfolder. Where can I provide the attachments?

**Comment by Hot12345** [comment]
> Hi @Hot12345
> 
> Do you mean that you want to export all the images of the documents into a folder?
> 
> If so you just need the `--extract-media "${outputPath}/images/"`

When Im doing export to WORD .docx
Then I get the document WITHOUT attachment.

That's because:
So this is clearly that Pandoc plugin can not find the picture when the picture (.pngfile) in a subfolder.
Also I checked in the settings of the plugin no such any kind of settings that it needs to search to a specific image in a nestled folder, instead of ;looking for a picture in the root folder.

Hope this make sense and can fix this bug/issue.
Still not being fixed.

What to do to fix this issue that the plugin search below in directory's?

**Comment by universvm** [comment]
Hi @Hot12345 

Okay as I understand that your .docx document does not have any image embedded in it. 

Are you keeping these images into obsidian? If so you need to add the following to your "Extra Arguments":

`--resource-path /your/path/to/where_you_keep_your_images/`

eg. If you are on Mac and keep Obsidian synced with iCloud it will look like this:

`--resource-path ~/Library/Mobile\ Documents/iCloud\~md\~obsidian/Documents/VAULTNAME/Images/`

In the above I keep my obsidian images in the "Image" Folder. 

You may find this article helpful as it goes over all of this and more: https://betterhumans.pub/obsidian-tutorial-for-academic-writing-87b038060522

**Comment by Hot12345** [comment]
> 

Hi @universvm , 

Yeah that's correct. If Im exporting the note.md file to Export to - .Docx document
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/29144713/74701ba5-3abc-47c5-9ea9-9c738465b119)

In the exported document: [[Pasted image 20230605124945.png]] but no picture. 
My pictures of my vault are listed in this directory: C:\Users\AygulKorkmazlar\Documents\GitHub\WorkVault\PNG\

So How and where can I tell this plugin to search the pictures and embedded them in the document?

**Comment by Hot12345** [comment]
Still not working. While added your --resource-path C:\Users\AygulKorkmazlar\Documents\GitHub\WorkVault\PNG\  to "Extra Arguments" in the screenshot.
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/29144713/408aecec-26e8-437b-b7e2-cc6ad51840a6)
![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/29144713/d4d4c3c7-e30a-4e6f-b0e3-ca59dc673b8d)

**Comment by Hot12345** [comment]
Do I miss the '' '' ''?
In the: --resource-path C:\Users\AygulKorkmazlar\Documents\GitHub\WorkVault\PNG\

**Comment by universvm** [comment]
Can you try referencing the image like so instead?

`![](Pasted Image XYZ.png) `

**Comment by Hot12345** [comment]
> Can you try referencing the image like so instead?
> 
> `![](Pasted Image XYZ.png) `

How do I that?

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/29144713/db9b545e-1a3b-4b81-b400-18b7b6297cfa)

![image](https://github.com/mokeyish/obsidian-enhancing-export/assets/29144713/cefdc52c-edd5-41dd-9975-2dafb309d6a4)

**Comment by universvm** [comment]
[[Pasted Image XYZ.png]] --> ![](Pasted Image XYZ.png)

**Comment by Hot12345** [comment]
> 

Hmmm do I need to change manually every picture naming? I did with one example. didn't workout.

**Comment by sun2ot** [comment]
> > 
> 
> Hmmm do I need to change manually every picture naming? I did with one example. didn't workout.

I am outside without computer... I remember there is a embed plugin in Obsidian. You can find it in Ob settings. That can help you to insert pictures by standard markdown grammar instead of `wiki` links.

And for pictures that had been inserted, like what did I say, using tools that can replace characters batches. such as Notepad3. You can replace double 
 `[` to `![]` and double `]` to blanks.

**Comment by universvm** [comment]
@Hot12345 did you resolve the issue?

**Comment by Hot12345** [comment]
> @Hot12345 did you resolve the issue?

Hi @universvm 
No, unfortunately, it didn't fix the issue.

**Comment by vanem** [comment]
The problem is that the plugin does not Wikilinks style of links, which are the default (see Settings/Options/Files & Links). Wikilinks style links are created for example when you paste an image in a note. If you use Markdown style links, the plugin works as expected. See https://github.com/mokeyish/obsidian-enhancing-export/issues/74

**Comment by mokeyish** [comment]
#154
