### ISSUE TITLE
Style - remove double ellipsis

### ISSUE THREAD

**Issue by luckman212** [mokeyish/obsidian-enhancing-export#88]
<img width="251" alt="screenshot_q18XfqUl_gh" src="https://github.com/mokeyish/obsidian-enhancing-export/assets/1992842/7ca0f03e-b2d5-46d6-afd9-7011d29373a2">

Minor thing, but the double-ellipsis does not follow standard UI guidelines, so it looks a bit odd. There shouldn't be a space between the text and the ellipsis either.

Instead of
https://github.com/mokeyish/obsidian-enhancing-export/blob/8d1cc285bf34b46738cc55876ff095b6e5407433/src/lang/en-US.ts#L4

Should be
```
exportToOo: 'Export to...', 
```

**Comment by mokeyish** [comment]
Hi，

Would you like to submit a PR to make changes?

**Comment by luckman212** [comment]
Sure @mokeyish - PR #89 submitted!
