### ISSUE TITLE
"pandoc command not found" on Linux

### ISSUE THREAD

**Issue by SepehrSemper** [mokeyish/obsidian-enhancing-export#93]
I'm using Obsidian on Fedora Linux, and nothing I have tried did solve the issue. 

If I run `$ whereis pandoc`, I get `pandoc: /usr/bin/pandoc /usr/share/man/man1/pandoc.1.gz`

And here's the output of `$ echo $PATH`: `/usr/bin/pandoc:/home/myusername/.local/bin:/home/myusername/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin`.

Directly typing  `/usr/bin/pandoc` in the field on the settings page doesn't change the situation.

**Comment by eander17** [comment]
Same here. Using Obsidian on Pop os. Added pandoc to path, specified /usr/bin/pandoc as well as /usr/share/pandoc. Nothing worked.

**Comment by mokeyish** [comment]
Please use the shortcut Ctrl+Shift+I or the <F12> key to open DevTools in the Obsidian.
Then see what the export command and options are.

https://github.com/mokeyish/obsidian-enhancing-export/blob/e64211c4d4f9aad24c902c46dad5f5d63bc834e1/src/exporto0o.ts#L176-L179

**Comment by SepehrSemper** [comment]
@mokeyish If you mean pasting that code snippet into the console, here's the console log:
```
 console.log(`[${plugin.manifest.name}]: export command and options:`, { 
   cmd, 
   options: { cwd: variables.currentDir, env }, 
 });
VM924:1 Uncaught ReferenceError: plugin is not defined
    at <anonymous>:1:18
(anonymous) @ VM924:1
```

**Comment by mokeyish** [comment]
Currently, You can set `PATH` environment variable in the plugin settings tab.
